# Funding links displayed on the GitHub "Sponsor" button
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [supernovae-st]
