# yamllint configuration for Nika workflows
# https://yamllint.readthedocs.io/en/stable/

extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  document-start: disable

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

  comments:
    min-spaces-from-content: 1

  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  key-duplicates: enable

  trailing-spaces: enable

  new-line-at-end-of-file: enable

  quoted-strings:
    quote-type: any
    required: only-when-needed

ignore: |
  node_modules/
  target/
  .git/
  .nika/
