// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! Shared HTTP-wire scaffold — multipart framing + the spec transient
//! table. Born in `media/wire.rs` for the image/tts provider adapters
//! (the 7×-copied set); promoted crate-level once `nika:fetch` grew
//! `multipart:` (generic uploads are a NET concern, not a media one).
//!
//! Two hardenings landed with the promotion — both mattered only once
//! parts stopped being studio-controlled (media payloads are our own
//! generated bytes; fetch parts are WORKFLOW-controlled):
//!
//! - **Boundary is content-keyed, not constant.** A fixed boundary
//!   inside attacker-influenced file bytes would terminate a part early
//!   and inject crafted form fields (request-splitting class). The
//!   boundary derives from a blake3 of every part — deterministic for
//!   identical input (golden-friendly · no RNG), and a body cannot
//!   practically contain the digest of itself. A counter-suffix belt
//!   handles the theoretical residue.
//! - **Header tokens are vetted.** `name`/`filename`/`mime` ride inside
//!   `Content-Disposition`/`Content-Type` lines — a quote or CR/LF
//!   there is header injection, so they are rejected loudly.

/// Encode `application/x-www-form-urlencoded` pairs (WHATWG form rules:
/// space → `+`, unreserved ALPHA/DIGIT/`-_.~` verbatim, every other
/// byte percent-encoded — multibyte UTF-8 lands as its encoded bytes).
pub(crate) fn form_urlencode(pairs: &[(&str, String)]) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    fn encode_into(out: &mut String, raw: &str) {
        for byte in raw.bytes() {
            match byte {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                    out.push(byte as char);
                }
                b' ' => out.push('+'),
                other => {
                    out.push('%');
                    out.push(HEX[usize::from(other >> 4)] as char);
                    out.push(HEX[usize::from(other & 0x0f)] as char);
                }
            }
        }
    }
    let mut out = String::new();
    for (i, (key, value)) in pairs.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        encode_into(&mut out, key);
        out.push('=');
        encode_into(&mut out, value);
    }
    out
}

/// Is this HTTP status transient (worth a retry)? The spec's status table:
/// 5xx server errors + 408 Request Timeout + 429 Too Many Requests. THE
/// single authority — `retry.on_codes` correctness rides on it matching
/// the spec across every media provider.
pub(crate) fn transient_status(status: u16) -> bool {
    matches!(status, 500..=599 | 408 | 429)
}

/// One field of a `multipart/form-data` body — a text value or a named
/// file part (media edit wires · fetch `multipart:` uploads).
pub(crate) enum Part<'a> {
    Text {
        name: &'a str,
        value: &'a str,
    },
    File {
        name: &'a str,
        filename: &'a str,
        mime: &'a str,
        bytes: &'a [u8],
    },
}

/// The boundary stem — the content-keyed digest is appended per body.
const BOUNDARY_STEM: &str = "----nika-media-boundary-";

/// How many counter-suffixed candidates to try after the digest-keyed
/// boundary before giving up. Reaching even the FIRST fallback needs a
/// body that contains the blake3 digest of itself — the cap exists so
/// the loop is provably total, not because it is reachable.
const BOUNDARY_ATTEMPTS: u32 = 8;

/// A header-line token (`name` · `filename` · `mime`) must not smuggle
/// framing or header bytes: quotes close the quoted-string, CR/LF start
/// a new header line (injection class).
fn vet_token(role: &str, value: &str) -> Result<(), String> {
    if value.contains('"') || value.contains('\r') || value.contains('\n') {
        return Err(format!(
            "multipart {role} `{}` may not contain quotes or line breaks",
            value.escape_default()
        ));
    }
    Ok(())
}

/// Whether `needle` occurs in any part's header tokens, text value or
/// file bytes — the collision test that keeps framing unambiguous.
fn any_part_contains(parts: &[Part<'_>], needle: &str) -> bool {
    let n = needle.as_bytes();
    parts.iter().any(|part| match part {
        Part::Text { name, value } => name.contains(needle) || value.contains(needle),
        Part::File {
            name,
            filename,
            mime,
            bytes,
        } => {
            name.contains(needle)
                || filename.contains(needle)
                || mime.contains(needle)
                || bytes.windows(n.len()).any(|w| w == n)
        }
    })
}

/// Pick the boundary: stem + blake3(parts) hex, then counter-suffixed
/// fallbacks. Deterministic per content.
fn boundary_for(parts: &[Part<'_>]) -> Result<String, String> {
    let mut hasher = blake3::Hasher::new();
    for part in parts {
        match part {
            Part::Text { name, value } => {
                hasher.update(name.as_bytes());
                hasher.update(b"\0");
                hasher.update(value.as_bytes());
            }
            Part::File {
                name,
                filename,
                mime,
                bytes,
            } => {
                hasher.update(name.as_bytes());
                hasher.update(b"\0");
                hasher.update(filename.as_bytes());
                hasher.update(b"\0");
                hasher.update(mime.as_bytes());
                hasher.update(b"\0");
                hasher.update(bytes);
            }
        }
        hasher.update(b"\x1f");
    }
    let digest = hasher.finalize().to_hex();
    let keyed = format!("{BOUNDARY_STEM}{}", &digest.as_str()[..16]);
    if !any_part_contains(parts, &keyed) {
        return Ok(keyed);
    }
    for n in 0..BOUNDARY_ATTEMPTS {
        let candidate = format!("{keyed}-{n}");
        if !any_part_contains(parts, &candidate) {
            return Ok(candidate);
        }
    }
    Err("multipart boundary could not be made collision-free".to_owned())
}

/// Build a `multipart/form-data` body + the matching `content-type`
/// header value. Parts are emitted in the given order — callers control
/// ordering (xai's edit wire documents `file` LAST). Fails loudly on
/// header-injectable tokens (never sanitize-and-continue).
pub(crate) fn multipart(parts: &[Part<'_>]) -> Result<(Vec<u8>, String), String> {
    for part in parts {
        match part {
            Part::Text { name, .. } => vet_token("part name", name)?,
            Part::File {
                name,
                filename,
                mime,
                ..
            } => {
                vet_token("part name", name)?;
                vet_token("filename", filename)?;
                vet_token("content type", mime)?;
            }
        }
    }
    let boundary = boundary_for(parts)?;
    let mut body = Vec::new();
    for part in parts {
        body.extend_from_slice(format!("--{boundary}\r\n").as_bytes());
        match part {
            Part::Text { name, value } => {
                body.extend_from_slice(
                    format!("Content-Disposition: form-data; name=\"{name}\"\r\n\r\n").as_bytes(),
                );
                body.extend_from_slice(value.as_bytes());
            }
            Part::File {
                name,
                filename,
                mime,
                bytes,
            } => {
                body.extend_from_slice(
                    format!(
                        "Content-Disposition: form-data; name=\"{name}\"; filename=\"{filename}\"\r\n"
                    )
                    .as_bytes(),
                );
                body.extend_from_slice(format!("Content-Type: {mime}\r\n\r\n").as_bytes());
                body.extend_from_slice(bytes);
            }
        }
        body.extend_from_slice(b"\r\n");
    }
    body.extend_from_slice(format!("--{boundary}--\r\n").as_bytes());
    Ok((body, format!("multipart/form-data; boundary={boundary}")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn multipart_frames_text_and_file_parts_with_the_boundary() {
        let (body, ct) = multipart(&[
            Part::Text {
                name: "model",
                value: "gpt-image-2",
            },
            Part::File {
                name: "image[]",
                filename: "src.png",
                mime: "image/png",
                bytes: b"\x89PNG",
            },
        ])
        .expect("clean parts frame");
        assert!(ct.contains("boundary=----nika-media-boundary"));
        let s = String::from_utf8_lossy(&body);
        assert!(s.contains("name=\"model\"\r\n\r\ngpt-image-2"));
        assert!(s.contains("filename=\"src.png\"") && s.contains("Content-Type: image/png"));
        assert!(s.trim_end().ends_with("--"), "closing delimiter");
        // raw file bytes ride verbatim (multipart files are NOT base64).
        assert!(body.windows(4).any(|w| w == b"\x89PNG"));
    }

    #[test]
    fn boundary_is_deterministic_per_content_and_differs_across_content() {
        let parts = || {
            vec![Part::Text {
                name: "a",
                value: "b",
            }]
        };
        let (_, ct1) = multipart(&parts()).expect("frame");
        let (_, ct2) = multipart(&parts()).expect("frame");
        assert_eq!(ct1, ct2, "same content → same boundary (golden-friendly)");
        let (_, ct3) = multipart(&[Part::Text {
            name: "a",
            value: "c",
        }])
        .expect("frame");
        assert_ne!(ct1, ct3, "different content → different boundary");
    }

    #[test]
    fn file_bytes_containing_a_boundary_run_cannot_break_framing() {
        // Adversarial: the file embeds a full plausible boundary line for
        // the OLD constant scheme AND arbitrary stem text — the chosen
        // boundary must still not occur inside the part.
        let hostile = b"--".to_vec().into_iter()
            .chain(b"----nika-media-boundary-7f3a9c2e\r\nContent-Disposition: form-data; name=\"evil\"\r\n\r\ninjected".iter().copied())
            .collect::<Vec<u8>>();
        let parts = [Part::File {
            name: "file",
            filename: "dump.bin",
            mime: "application/octet-stream",
            bytes: &hostile,
        }];
        let (body, ct) = multipart(&parts).expect("frame");
        let boundary = ct
            .split("boundary=")
            .nth(1)
            .expect("content-type carries the boundary");
        let delim = format!("--{boundary}");
        // The delimiter occurs exactly twice as framing (open + close),
        // never inside the payload region.
        let count = body
            .windows(delim.len())
            .filter(|w| *w == delim.as_bytes())
            .count();
        assert_eq!(count, 2, "framing only — no in-payload collision");
        assert!(
            !hostile
                .windows(boundary.len())
                .any(|w| w == boundary.as_bytes()),
            "chosen boundary absent from the hostile bytes"
        );
    }

    #[test]
    fn header_injectable_tokens_are_rejected_loudly() {
        for (name, filename) in [
            ("ok\"evil", "f.png"),
            ("ok", "f\r\nX-Smuggled: 1.png"),
            ("nl\ninject", "f.png"),
        ] {
            let err = multipart(&[Part::File {
                name,
                filename,
                mime: "image/png",
                bytes: b"x",
            }])
            .expect_err("injectable token must be refused");
            assert!(
                err.contains("may not contain"),
                "names the violation: {err}"
            );
        }
    }

    #[test]
    fn transient_matches_the_spec_status_table() {
        for s in [500, 502, 503, 599, 408, 429] {
            assert!(transient_status(s), "{s} is transient");
        }
        for s in [200, 400, 401, 403, 404, 422] {
            assert!(!transient_status(s), "{s} is terminal");
        }
    }
}
