// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
//
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
// Pack integrity — the embedded snapshot must match its own manifest.
//
// The manifest (generated by the spec's showcase-projector) carries a
// sha256_16 over the LEAN text of every workflow. Re-hashing the
// embedded bytes here means a tampered, truncated or drifted vendored
// pack fails `cargo test` — the binary can never silently ship a pack
// that disagrees with the spec version it claims.

use sha2::{Digest, Sha256};

fn sha256_16(text: &str) -> String {
    // the manifest hashes lean + trailing newline (python lean() keeps it)
    let mut h = Sha256::new();
    h.update(text.as_bytes());
    h.update(b"\n");
    let digest = h.finalize();
    let mut out = String::with_capacity(16);
    for b in digest.iter().take(8) {
        use std::fmt::Write as _;
        let _ = write!(out, "{b:02x}");
    }
    out
}

/// Parse `file:` / `sha256_16:` pairs out of the manifest.
fn manifest_entries() -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<String> = None;
    for line in nika_pack::manifest().lines() {
        let line = line.trim();
        if let Some(f) = line.strip_prefix("- file: ") {
            current = Some(f.trim().to_owned());
        } else if let Some(h) = line.strip_prefix("sha256_16: ")
            && let Some(f) = current.take()
        {
            out.push((f, h.trim().to_owned()));
        }
    }
    out
}

#[test]
fn version_is_nonempty_and_matches_manifest() {
    let v = nika_pack::pack_version();
    assert!(!v.is_empty());
    let line = format!("pack_version: {v}");
    assert!(
        nika_pack::manifest().contains(&line),
        "manifest pack_version must equal the embedded VERSION ({v})"
    );
}

#[test]
fn every_manifest_entry_resolves_and_hashes_clean() {
    let entries = manifest_entries();
    assert!(
        entries.len() >= 27,
        "expected the full pack · got {}",
        entries.len()
    );
    for (file, expected) in entries {
        let slug = file
            .strip_prefix("examples/")
            .map(str::to_owned)
            .or_else(|| {
                file.strip_prefix("templates/")
                    .map(|s| format!("templates::{s}"))
            });
        let text = match slug {
            Some(s) if s.starts_with("templates::") => {
                nika_pack::template(s.trim_start_matches("templates::"))
            }
            Some(s) => nika_pack::example(&s),
            None => None,
        };
        let text = text.unwrap_or_else(|| panic!("manifest entry {file} not embedded"));
        let lean = nika_pack::lean(text);
        assert_eq!(
            sha256_16(lean),
            expected,
            "embedded {file} drifted from its manifest hash"
        );
    }
}

#[test]
fn surface_counts_hold() {
    // A FLOOR here, never a typed count. The exact surface is asserted by NAME
    // against the vendored canon in `spec_parity::canon_templates_equal_the_
    // embedded_surface` — a hand-typed equality only ever noticed that a number
    // moved, and had to be edited by hand at 9→10 and again at 10→14.
    let names = nika_pack::template_names();
    assert!(names.len() >= 10);
    // The four form-first skeletons are pinned BY NAME here, and that is not a
    // duplicate of the parity test: parity proves embedded == canon-declared,
    // which still passes if a removal takes BOTH sides down together. This is
    // the floor that refuses that.
    for required in [
        "classify-and-route",
        "corpus-qa",
        "document-to-fields",
        "evaluate-and-optimize",
    ] {
        assert!(
            names.iter().any(|n| n == required),
            "form-first skeleton {required} missing from the vendored pack"
        );
    }
    assert!(nika_pack::example_slugs().len() >= 27);
    assert!(nika_pack::doc_paths().len() >= 12, "spec + stdlib pages");
    assert!(nika_pack::schema_json().contains("\"$schema\""));
    assert!(nika_pack::canon().contains("schema_version:"));
    // content assertions (not just non-empty) — mutation-hardened
    assert!(nika_pack::quickstart().contains("nika"));
    let verbs = nika_pack::doc("spec/02-verbs.md").expect("verbs page embedded");
    assert!(verbs.contains("infer"));
    assert!(nika_pack::doc("stdlib/builtins-v0.1.md").is_some());
    assert!(nika_pack::doc("no/such/page.md").is_none());
}

#[test]
fn manifest_and_embedded_sets_are_bijective() {
    // bidirectional · a file added to pack/ without a manifest regen (or
    // dropped from the manifest) fails here — drift cannot ride along.
    let entries = manifest_entries().len();
    let embedded = nika_pack::example_slugs().len() + nika_pack::template_names().len();
    assert_eq!(
        entries, embedded,
        "manifest entries vs embedded workflows+templates"
    );
}

#[test]
fn lean_strips_the_banner_and_nothing_else() {
    let text = "# SPDX\n# banner\nnika: x\n";
    assert_eq!(nika_pack::lean(text), "nika: x");
    // no banner → identity
    assert_eq!(nika_pack::lean("nika: solo\n"), "nika: solo");
    // the hashing invariant · lean() trims ALL trailing newlines and the
    // hasher re-appends exactly one — mirrors the spec projector's lean()
    // (python keeps one trailing \n). Multi-newline tails normalize.
    assert_eq!(nika_pack::lean("nika: solo\n\n"), "nika: solo");
}

#[test]
fn error_codes_registry_parses_typed_and_complete() {
    // THE one parser for the canon error_codes rows — every consumer
    // (explain's teach surface · the emitted⊆registered ratchet) reads
    // through this accessor, so its contract is pinned at the seam:
    let rows = nika_pack::error_codes();
    // ≥ the v0.1 normative floor (49 at vendoring · never hand-pin the
    // live count — the canon's own count field is the cross-check).
    assert!(
        rows.len() >= 30,
        "registry parse broke ({} rows)",
        rows.len()
    );
    let declared: usize = nika_pack::canon()
        .lines()
        .skip_while(|l| !l.starts_with("error_codes:"))
        .take_while(|l| {
            l.starts_with([' ', '#']) || l.starts_with("error_codes:") || l.trim().is_empty()
        })
        .find_map(|l| {
            l.trim()
                .strip_prefix("count:")
                .and_then(|v| v.trim().parse().ok())
        })
        .expect("canon declares error_codes.count");
    assert_eq!(rows.len(), declared, "parsed rows vs the canon's own count");

    // Spot-pin one row fully (the beginner's #1 error in W2 — the dead
    // depends_on teaching; DAG-003 is RETIRED and must NOT resurface).
    let p24 = rows
        .iter()
        .find(|r| r.code == "NIKA-PARSE-024")
        .expect("NIKA-PARSE-024 row");
    assert_eq!(p24.category, "validation_error");
    assert_eq!(p24.transient, "false");
    assert!(p24.failure.len() > 10);
    assert!(
        !rows.iter().any(|r| r.code == "NIKA-DAG-003"),
        "NIKA-DAG-003 is retired-never-reuse — a row means the canon regressed"
    );

    // Every row is well-formed + the escape-free invariant the anchored
    // parse relies on (an escaped quote would silently truncate).
    for r in &rows {
        assert!(r.code.starts_with("NIKA-"), "{r:?}");
        assert!(!r.category.is_empty() && !r.failure.is_empty(), "{r:?}");
        assert!(!r.failure.contains('\\'), "escape in failure text: {r:?}");
    }

    // Anchoring: codes are unique (a same-shaped row from another canon
    // table leaking in would collide or inflate the count).
    let mut codes: Vec<_> = rows.iter().map(|r| r.code).collect();
    codes.sort_unstable();
    codes.dedup();
    assert_eq!(codes.len(), rows.len(), "duplicate codes in the registry");
}

/// Issue 1040 · an agent read `count: 103` plus two `NIKA-BUILTIN-*` rows
/// as the whole builtin-code family. The family lives in `nika explain`.
/// The count must say so on the same surface (`nika spec --canon`).
#[test]
fn error_codes_count_says_the_floor_is_not_the_family() {
    let canon = nika_pack::canon();
    let section: String = canon
        .lines()
        .skip_while(|l| !l.starts_with("error_codes:"))
        .take_while(|l| {
            l.starts_with([' ', '#']) || l.starts_with("error_codes:") || l.trim().is_empty()
        })
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        section.contains("not enumerated here"),
        "the error_codes count must say per-builtin codes resolve through explain:\n{section}"
    );
}

/// B01 · `hello` and `01-hello` are ONE file. Product hello-on-mock lives
/// in nika-onboard / nika-cli-host, not in the vendored spec YAML.
#[test]
fn hello_aliases_01_hello() {
    let hello = nika_pack::example("hello").expect("hello resolves");
    let numbered = nika_pack::example("01-hello").expect("01-hello resolves");
    assert_eq!(
        hello, numbered,
        "nika new hello · nika new 01-hello · nika try 01-hello share one body"
    );
    assert!(
        numbered.lines().any(|l| l.starts_with("model: ")),
        "the one hello carries a model seat"
    );
}

/// B16 · a comment that says « local » next to a non-local seat is a lie.
#[test]
fn hello_comments_match_the_model_field() {
    let body = nika_pack::example("01-hello").expect("embedded");
    let model = body
        .lines()
        .find(|l| l.starts_with("model: "))
        .expect("model line");
    let seat = model
        .trim_start_matches("model: ")
        .split('#')
        .next()
        .expect("seat")
        .trim();
    let comment = model.split_once('#').map(|(_, c)| c.to_ascii_lowercase());
    if seat.starts_with("mock/") {
        if let Some(c) = comment {
            assert!(
                !c.contains("local") && !c.contains("openai"),
                "mock/echo comment must not claim local/openai: {model}"
            );
        }
        for line in body
            .lines()
            .take_while(|l| l.starts_with('#') || l.is_empty())
        {
            let lower = line.to_ascii_lowercase();
            assert!(
                !lower.contains("one local model"),
                "header must match the mock/echo field: {line}"
            );
        }
    } else if (seat.starts_with("openai/") || seat.starts_with("anthropic/"))
        && let Some(c) = comment
    {
        assert!(
            !c.contains("local"),
            "cloud seat comment must not say local: {model}"
        );
    }
}

/// I08 · `gpt-4o-mini` is not an openai catalog seat (`gpt-5.2` / `gpt-5-mini`).
/// A scaffold that names it is teaching a model the resolver should refuse.
#[test]
fn scaffolds_never_name_gpt_4o_mini_unless_catalog_lists_it() {
    let catalogued = nika_catalog::all_providers().iter().any(|p| {
        p.models
            .iter()
            .any(|m| m.model == "gpt-4o-mini" || m.id == "gpt-4o-mini")
    });
    let mut hits = Vec::new();
    for slug in nika_pack::example_slugs() {
        if nika_pack::example(&slug).is_some_and(|b| b.contains("gpt-4o-mini")) {
            hits.push(format!("example:{slug}"));
        }
    }
    for name in nika_pack::template_names() {
        if nika_pack::template(&name).is_some_and(|b| b.contains("gpt-4o-mini")) {
            hits.push(format!("template:{name}"));
        }
    }
    if catalogued {
        return;
    }
    assert!(
        hits.is_empty(),
        "gpt-4o-mini is absent from the openai catalog; scaffolds must not name it: {hits:?}"
    );
}

/// UX-1 · first shelf is five jobs; the rest live behind `try --all`.
/// B06/C06 stay off the weekend shelf (host cargo / git).
#[test]
fn first_shelf_is_hello_brief_image_fetch_notify() {
    let shelf = nika_pack::first_shelf();
    assert_eq!(
        shelf.len(),
        5,
        "first_shelf is five jobs, not the full corpus"
    );
    assert_eq!(
        shelf,
        [
            "01-hello",
            "ceo-monday-brief",
            "og-images",
            "05-fetch-chain",
            "release-notes"
        ]
    );
    for slug in shelf {
        assert!(
            nika_pack::example(slug).is_some(),
            "first-shelf slug `{slug}` must exist in the pack"
        );
        assert!(
            nika_pack::try_recover_hint(slug).is_none(),
            "first-shelf `{slug}` must rehearse without a host-toolchain hint"
        );
    }
    assert!(
        !shelf.contains(&"03-exec-pipeline"),
        "03-exec-pipeline is not a first-shelf job (B06 · --all only)"
    );
    assert!(
        !shelf.contains(&"standup-digest"),
        "standup-digest is not a first-shelf job (C06 · --all only)"
    );
    assert_eq!(
        nika_pack::example("hello"),
        nika_pack::example("01-hello"),
        "hello aliases 01-hello on the same first-shelf file"
    );
}

/// B06 · missing cargo is a recovered red suite, not an opaque NIKA-SEC-001.
/// The spec YAML does not carry `on_error: recover` — the hint lives in Rust.
#[test]
fn exec_pipeline_recovers_when_cargo_is_missing() {
    let body = nika_pack::example("03-exec-pipeline").expect("embedded");
    assert!(
        body.to_ascii_lowercase().contains("cargo"),
        "03-exec-pipeline still names cargo (the host tool)"
    );
    let hint = nika_pack::try_recover_hint("03-exec-pipeline").expect("B06 hint");
    assert_eq!(hint.missing, "cargo");
    assert_eq!(hint.recovered_as, "exit 127");
}

/// C06 · not-a-git-repo is a recovered empty history, not seatbelt 128.
/// The spec YAML does not carry `on_error: recover` — the hint lives in Rust.
#[test]
fn standup_digest_recovers_when_git_is_missing() {
    let body = nika_pack::example("standup-digest").expect("embedded");
    assert!(
        body.contains("git"),
        "standup-digest still names git (the host tool)"
    );
    let hint = nika_pack::try_recover_hint("standup-digest").expect("C06 hint");
    assert_eq!(hint.missing, "git");
    assert_eq!(hint.recovered_as, "empty log");
}
