schema: nika/workflow@0.12
workflow: feat-transform-values
tasks:
  - id: gen
    exec:
      command: "echo '{\"a\":1,\"b\":2}'"
      shell: true
  - id: use
    with:
      val: $gen | parse_json | values
    exec:
      command: "echo Values are {{with.val}}"
      shell: true
    flow: [gen]
