// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! The one instruction the explicitly permitted seat reads before it proposes a
//! private semantic plan: the closed vocabulary of steps, effects, obligations and
//! regions, in the request's own words. Text only, no logic; the decoder in
//! [`super`] owns what is accepted.

pub(super) const INSTRUCTIONS: &str = r"Interpret the ENTIRE user request, in whatever language, as a private semantic plan for a workflow compiler. Return only one JSON object with steps, effects, obligations, constraints, unknowns, regions, approval_bypass. Never produce YAML, source, tool calls, credentials, endpoints or permissions.
steps: the operations requested, in order. op is one of read (consume a document, text, file, transcript, local folder, glob or set of named files the requester supplies with the invocation; never a named system or store), fetch (retrieve one web page by an explicit URL in the request), lookup (retrieve existing records or values from any named external system, store, service, database, directory, catalog, calendar, dashboard, history, registry, runbook or knowledge base; consulting, reading, checking or querying such a source is lookup even when the request says read), search (find passages or files in a corpus of documents by a query), extract (pull structured fields out of free text, a form, a PDF or a transcript), classify (categorize or route into named categories; list the categories verbatim when named), draft (write, summarize, translate, propose in writing, correct or draft text without sending it), compute (a threshold, comparison, total, count, average, grouping, sort or projection that must run as code over a parsed table; state it as computation {present: true, polarity: keep|drop, join: and|or, clauses: [{field, op: gt|ge|lt|le|eq|ne, value, value_field}], group_by, aggregations: [{field, op: sum|count|avg|min|max, as, round}], sort_by, order: asc|desc, columns} using the request's own column names, output names and literal values exactly as the request states them, never rewriting a comparison: clauses describe the rows kept (polarity keep) or excluded (polarity drop) and are empty when every row counts; value_field names another column when two columns compare and is empty otherwise; group_by names the column one output row per distinct value is made for, empty otherwise; each aggregation names the output field the request states (as), the source column it aggregates (field, empty for count) and the number of decimals when the request rounds (round, empty otherwise); sort_by and order name the ordering the request states, empty otherwise; columns lists the output columns in the order the request fixes them, empty otherwise; derived lists the outputs the request defines as arithmetic over other outputs ({as, op: sub|add|mul|div, left, right} where left and right name outputs already produced or a number of the request; such an output is never an aggregation); computation.present is false when the step is not such a computation), validate (verify against explicit criteria), explore (an open-ended region the request explicitly delegates to agents, bounded by turns). detail is the verbatim object of the operation. evidence is an exact nonempty verbatim substring of the request.
effects: every action that changes the outside world (create a record, send, publish, post, open a ticket, trigger a payment, mark, order, refund, merge, notify, delete, write a file). verb is one of create, send, publish, update, notify, refund, pay, order, merge, delete, write, effect. target is the verbatim phrase naming the action. policy is one of automatic (requested without a prior human requirement), human_first (only after a fresh explicit human validation of that exact action), forbidden (explicitly prohibited), unspecified (the requester explicitly has not decided and wants to be asked), conflict (requested and prohibited at once). evidence is an exact verbatim substring. Never drop a requested effect; never add one.
obligations: kind is one of dedup (no second action for the same incoming identifier), retry_bound (a numeric maximum of attempts, cycles or iterations; put the number in value), revision_check (recheck the current version immediately before the final action). A price, deadline, record count or number of proposed time slots is not a bound.
constraints: verbatim instructions that shape how steps run (what not to infer, what to keep null, what remains a code rule, which sources are excluded).
unknowns: requested work outside this vocabulary (durable triggers are NOT unknown: one invocation per item is supported; named SaaS systems are NOT unknown: they are lookups or effects the compiler will ask an endpoint or file for; the contents of a named file, folder or record are runtime data, NOT unknown).
regions: partition the WHOLE request into contiguous verbatim excerpts, in order, covering every sentence, each with role operation | effect | policy | obligation | constraint | context | unknown. Nothing meaningful may be left out of regions; a region you cannot map gets role unknown.
approval_bypass: {present: true|false, evidence: verbatim substring} when the request asks to reuse a prior approval, skip approval, act without asking, or otherwise presuppose an approval it does not give.
Preserve the meaning expressed in the requester's language; never complete by guessing; never rewrite a literal (URL, path, number, currency, name).";
