//! Trust system for Nika Shield — compile-time and runtime data provenance tracking.
//!
//! Every value flowing through a Nika DAG has a trust level. The propagation rule
//! is conservative: `trust = min(all_input_trust_levels)`.
//!
//! This module lives in nika-core (L0) because the taint analyzer needs it at
//! compile-time (nika check --security) and the engine needs it at runtime.

use serde::{Deserialize, Serialize};

// ── TrustLevel ──────────────────────────────────────────────────────────────

/// Trust level for data flowing through the workflow DAG.
///
/// Propagation rule: `trust = min(all_input_trust_levels)`.
/// Ord: `Trusted(3) > ModelGenerated(2) > ModelTainted(1) > Untrusted(0)`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum TrustLevel {
    /// From external source: fetch responses, MCP tools, exec stdout.
    Untrusted = 0,
    /// Generated by an LLM that processed untrusted inputs.
    ModelTainted = 1,
    /// Generated by an LLM without any untrusted inputs.
    ModelGenerated = 2,
    /// Authored by workflow developer: YAML literals, CLI inputs, context files.
    Trusted = 3,
}

impl TrustLevel {
    /// Conservative merge: take the minimum trust level.
    #[inline]
    pub fn merge(self, other: Self) -> Self {
        std::cmp::min(self, other)
    }

    /// True if data should be treated as potentially adversarial.
    #[inline]
    pub fn is_untrusted(self) -> bool {
        matches!(self, Self::Untrusted | Self::ModelTainted)
    }
}

impl std::fmt::Display for TrustLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Trusted => write!(f, "Trusted"),
            Self::ModelGenerated => write!(f, "ModelGenerated"),
            Self::ModelTainted => write!(f, "ModelTainted"),
            Self::Untrusted => write!(f, "Untrusted"),
        }
    }
}

// ── InvocationSource ────────────────────────────────────────────────────────

/// How the workflow was invoked — determines input trust level.
///
/// CLI inputs are trusted (user typed them). HTTP inputs from `nika serve`
/// are untrusted (arbitrary clients). This is the single most important
/// trust decision — it determines the trust floor for the entire DAG.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvocationSource {
    /// Direct CLI invocation: inputs = Trusted.
    Cli,
    /// HTTP via `nika serve`: inputs = Untrusted.
    Serve,
    /// Test/mock execution: inputs = Trusted.
    Test,
}

impl InvocationSource {
    /// Trust level for workflow `inputs:` based on invocation source.
    #[inline]
    pub fn input_trust(self) -> TrustLevel {
        match self {
            Self::Cli | Self::Test => TrustLevel::Trusted,
            Self::Serve => TrustLevel::Untrusted,
        }
    }
}

impl std::fmt::Display for InvocationSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Cli => write!(f, "cli"),
            Self::Serve => write!(f, "serve"),
            Self::Test => write!(f, "test"),
        }
    }
}

// ── Builtin Trust Categorization ────────────────────────────────────────────

/// Builtins that pass data through — output trust = `min(input_trust, Trusted)`.
///
/// These tools transform or reshape data without adding trust. If the input
/// is untrusted, the output remains untrusted (an attacker can't launder
/// tainted data through `nika:jq`).
pub const TRUST_PROPAGATING_BUILTINS: &[&str] = &[
    "nika:jq",
    "nika:map",
    "nika:filter",
    "nika:chunk",
    "nika:zip",
    "nika:json_merge",
    "nika:inject",
    "nika:enrich",
    "nika:group_by",
    "nika:aggregate",
    "nika:json_flatten",
    "nika:json_unflatten",
    "nika:set_diff",
    "nika:json_diff",
    "nika:tree_data",
    "nika:json_verify",
    "nika:yaml_validate",
    "nika:read",
    "nika:glob",
    "nika:grep",
    "nika:html_to_md",
    "nika:css_select",
    "nika:readability",
    "nika:extract_metadata",
    "nika:extract_links",
    "nika:locale_lookup",
];

/// Builtins that produce trusted output regardless of input (pure side-effects
/// or metadata-only queries).
pub const TRUST_PURE_BUILTINS: &[&str] = &[
    "nika:sleep",
    "nika:log",
    "nika:emit",
    "nika:assert",
    "nika:cost",
    "nika:token_count",
    "nika:dag_info",
    "nika:task_status",
    "nika:threads",
    "nika:records",
    "nika:prompt",
    "nika:complete",
    "nika:dimensions",
    "nika:thumbhash",
    "nika:dominant_color",
];

/// Check if a builtin tool propagates input trust (vs producing trusted output).
pub fn is_trust_propagating_builtin(tool: &str) -> bool {
    TRUST_PROPAGATING_BUILTINS.contains(&tool)
}

/// Check if a builtin tool always produces trusted output.
pub fn is_trust_pure_builtin(tool: &str) -> bool {
    TRUST_PURE_BUILTINS.contains(&tool)
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trust_level_ordering() {
        assert!(TrustLevel::Trusted > TrustLevel::ModelGenerated);
        assert!(TrustLevel::ModelGenerated > TrustLevel::ModelTainted);
        assert!(TrustLevel::ModelTainted > TrustLevel::Untrusted);
    }

    #[test]
    fn test_trust_merge_takes_minimum() {
        assert_eq!(
            TrustLevel::Trusted.merge(TrustLevel::Untrusted),
            TrustLevel::Untrusted
        );
        assert_eq!(
            TrustLevel::ModelGenerated.merge(TrustLevel::ModelTainted),
            TrustLevel::ModelTainted
        );
        assert_eq!(
            TrustLevel::Trusted.merge(TrustLevel::Trusted),
            TrustLevel::Trusted
        );
    }

    #[test]
    fn test_trust_merge_commutative() {
        let pairs = [
            (TrustLevel::Trusted, TrustLevel::Untrusted),
            (TrustLevel::ModelGenerated, TrustLevel::ModelTainted),
            (TrustLevel::Trusted, TrustLevel::ModelGenerated),
        ];
        for (a, b) in pairs {
            assert_eq!(a.merge(b), b.merge(a), "merge({a}, {b}) not commutative");
        }
    }

    #[test]
    fn test_is_untrusted() {
        assert!(!TrustLevel::Trusted.is_untrusted());
        assert!(!TrustLevel::ModelGenerated.is_untrusted());
        assert!(TrustLevel::ModelTainted.is_untrusted());
        assert!(TrustLevel::Untrusted.is_untrusted());
    }

    #[test]
    fn test_invocation_source_trust() {
        assert_eq!(InvocationSource::Cli.input_trust(), TrustLevel::Trusted);
        assert_eq!(InvocationSource::Test.input_trust(), TrustLevel::Trusted);
        assert_eq!(
            InvocationSource::Serve.input_trust(),
            TrustLevel::Untrusted
        );
    }

    #[test]
    fn test_builtin_categorization_no_overlap() {
        for tool in TRUST_PROPAGATING_BUILTINS {
            assert!(
                !TRUST_PURE_BUILTINS.contains(tool),
                "{tool} is in both PROPAGATING and PURE lists"
            );
        }
    }

    #[test]
    fn test_is_trust_propagating_builtin() {
        assert!(is_trust_propagating_builtin("nika:jq"));
        assert!(is_trust_propagating_builtin("nika:map"));
        assert!(is_trust_propagating_builtin("nika:filter"));
        assert!(!is_trust_propagating_builtin("nika:sleep"));
        assert!(!is_trust_propagating_builtin("nika:log"));
        assert!(!is_trust_propagating_builtin("unknown:tool"));
    }

    #[test]
    fn test_is_trust_pure_builtin() {
        assert!(is_trust_pure_builtin("nika:sleep"));
        assert!(is_trust_pure_builtin("nika:log"));
        assert!(!is_trust_pure_builtin("nika:jq"));
        assert!(!is_trust_pure_builtin("unknown:tool"));
    }

    #[test]
    fn test_trust_level_display() {
        assert_eq!(TrustLevel::Trusted.to_string(), "Trusted");
        assert_eq!(TrustLevel::Untrusted.to_string(), "Untrusted");
        assert_eq!(TrustLevel::ModelTainted.to_string(), "ModelTainted");
        assert_eq!(TrustLevel::ModelGenerated.to_string(), "ModelGenerated");
    }

    #[test]
    fn test_invocation_source_display() {
        assert_eq!(InvocationSource::Cli.to_string(), "cli");
        assert_eq!(InvocationSource::Serve.to_string(), "serve");
        assert_eq!(InvocationSource::Test.to_string(), "test");
    }
}
