// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! The cue and marker tables of the deterministic reader, across its languages
//! (EN · FR · IT · ES): what settles an ambiguous retrieval, what a clause may be
//! led by, which words are articles, how a policy sentence announces itself.
//! Every table is closed; a cue absent here is a cue the reader does not know.

/// Cues that settle an ambiguous retrieval head deterministically.
pub(super) const LOOKUP_CUES: &[&str] = &[
    "mongodb",
    "base ",
    "database",
    "annuaire",
    "directory",
    "registre",
    "registry",
    "catalogue",
    "catalog",
    "historique",
    "history",
    "calendrier",
    "calendar",
    "crm",
    "shopify",
    "runbook",
    "checklist",
    "knowledge base",
    "disponibilit",
    "availabilit",
    "agenda",
    "base de connaissances",
    "record",
    "customer",
    "client",
    "entreprise",
    "compte",
    "banca dati",
    "base dati",
    "base de datos",
    "elenco",
    "directorio",
    "registro",
    "storico",
    "historial",
    "calendario",
    "conto",
    "cuenta",
    "azienda",
    "empresa",
    "listino",
];
pub(super) const SEARCH_CUES: &[&str] = &[
    "pdf",
    "dossier",
    "fichiers",
    "files",
    "folder",
    "pages",
    "documents",
    "guide",
    "passages",
    "corpus",
    "cartella",
    "carpeta",
    "documenti",
    "documentos",
    "archivos",
    "pagine",
    "páginas",
    "paginas",
    "guida",
    "guía",
    "guia",
    "passaggi",
    "pasajes",
];
pub(super) const READ_CUES: &[&str] = &[
    "fourni",
    "fournie",
    "fournis",
    "fournies",
    "supplied",
    "provided",
    "attached",
    "ci-joint",
    "formulaire",
    "form ",
    "transcript",
    "fornito",
    "fornita",
    "forniti",
    "fornite",
    "allegato",
    "allegata",
    "allegati",
    "proporcionado",
    "proporcionada",
    "adjunto",
    "adjunta",
    "suministrado",
    "formulario",
    "trascrizione",
    "transcripción",
    "transcripcion",
];
pub(super) const LEADING_FILLER: &[&str] = &[
    "ensuite ",
    "puis ",
    "then ",
    "also ",
    "aussi ",
    "please ",
    "veuillez ",
    "s'il te plaît ",
    "s'il vous plaît ",
    "automatically ",
    "automatiquement ",
    "seulement ",
    "only ",
    "always ",
    "toujours ",
    "poi ",
    "quindi ",
    "per favore ",
    "anche ",
    "sempre ",
    "soltanto ",
    "luego ",
    "después ",
    "despues ",
    "por favor ",
    "también ",
    "tambien ",
    "siempre ",
];
pub(super) const ARTICLES: &[&str] = &[
    "le", "la", "les", "l", "l'", "d", "qu", "n", "s", "c", "j", "un", "une", "des", "du", "de",
    "d'", "the", "a", "an", "my", "mon", "ma", "mes", "notre", "nos", "our", "son", "sa", "ses",
    "its", "their", "leur", "leurs", "ce", "cet", "cette", "ces", "chaque", "each", "every",
    "tout", "toute", "tous", "toutes", "any", "all", "en", "ensuite", "il", "lo", "gli", "i",
    "uno", "una", "dei", "delle", "degli", "della", "dello", "del", "di", "ogni", "tutti", "tutte",
    "questo", "questa", "questi", "queste", "mio", "mia", "miei", "mie", "nostro", "nostra", "suo",
    "sua", "el", "los", "las", "unos", "unas", "al", "cada", "todo", "todos", "todas", "este",
    "esta", "estos", "estas", "mi", "mis", "nuestro", "nuestra", "su", "sus",
];
pub(super) const TRIGGER_PREFIXES: &[&str] = &[
    "pour la ",
    "pour le ",
    "pour les ",
    "pour chaque ",
    "for the ",
    "for every ",
    "quand ",
    "lorsque ",
    "dès que ",
    "tous les ",
    "toutes les ",
    "chaque fois ",
    "après ",
    "for each ",
    "when ",
    "whenever ",
    "every ",
    "after ",
    "once ",
    "à partir de ",
    "from the ",
    "starting from ",
    "per ogni ",
    "per ciascun ",
    "per ciascuna ",
    "ogni ",
    "quando ",
    "a partire da ",
    "para cada ",
    "cada ",
    "cuando ",
    "a partir de ",
];

pub(super) const NUMBER_WORDS: &[(&str, u32)] = &[
    ("un", 1),
    ("une", 1),
    ("one", 1),
    ("deux", 2),
    ("two", 2),
    ("trois", 3),
    ("three", 3),
    ("quatre", 4),
    ("four", 4),
    ("cinq", 5),
    ("five", 5),
    ("six", 6),
    ("sept", 7),
    ("seven", 7),
    ("huit", 8),
    ("eight", 8),
    ("neuf", 9),
    ("nine", 9),
    ("dix", 10),
    ("ten", 10),
    ("uno", 1),
    ("due", 2),
    ("dos", 2),
    ("tre", 3),
    ("tres", 3),
    ("quattro", 4),
    ("cuatro", 4),
    ("cinque", 5),
    ("cinco", 5),
    ("seis", 6),
    ("sette", 7),
    ("siete", 7),
    ("otto", 8),
    ("ocho", 8),
    ("nove", 9),
    ("nueve", 9),
    ("dieci", 10),
    ("diez", 10),
];
pub(super) const ATTEMPT_NOUNS: &[&str] = &[
    "essai",
    "tentative",
    "itération",
    "iteration",
    "cycle",
    "attempt",
    "retr",
    "tries",
    "try",
    "round",
    "tentativ",
    "intento",
    "iterazion",
    "iteración",
    "iteracion",
    "ciclo",
];
pub(super) const BOUND_WORDS: &[&str] = &[
    "limite ",
    "limit ",
    "au maximum",
    "maximum",
    "at most",
    "up to",
    "no more than",
    "at max",
    "max ",
    "al massimo",
    "massimo",
    "non più di",
    "como máximo",
    "como maximo",
    "máximo",
    "maximo",
    "no más de",
    "no mas de",
];
pub(super) const UNDECIDED_MARKERS: &[&str] = &[
    "je n'ai pas encore décidé si le workflow doit ",
    "je n'ai pas encore décidé si le workflow devait ",
    "je n'ai pas encore décidé si ",
    "i have not decided whether the workflow should ",
    "i have not decided whether to ",
    "i have not decided whether ",
    "i haven't decided whether to ",
    "i haven't decided whether ",
];
pub(super) const REVISION_MARKERS: &[&str] = &[
    "vérifie de nouveau la version",
    "vérifie à nouveau la version",
    "re-check the current",
    "recheck the current",
    "check the current version again",
    "re-verify the current",
];
pub(super) const FINAL_GATE_MARKERS: &[&str] = &[
    "mais cette action finale exige la validation humaine",
    "cette action finale exige la validation humaine",
    "this final action requires human validation",
    "this final action requires human approval",
    "only after my approval",
    "only after i approve",
    "only once i approve",
    "once i approve",
    "after my approval",
    "seulement après mon accord",
    "après mon accord",
    "après ma validation",
    "après validation humaine",
    "but ask me before",
    "but get my approval before",
    "get my approval before",
    "with my approval before",
    "solo dopo la mia approvazione",
    "dopo la mia approvazione",
    "solo dopo il mio consenso",
    "dopo il mio consenso",
    "sólo después de mi aprobación",
    "solo después de mi aprobación",
    "después de mi aprobación",
    "solo despues de mi aprobacion",
    "despues de mi aprobacion",
    "solo con mi aprobación",
];
pub(super) const NAMED_GATE_MARKERS: &[&str] = &[
    "demande mon accord avant ",
    "demandez mon accord avant ",
    "demander mon accord avant ",
    "demande un accord humain avant ",
    "demande ma validation avant ",
    "require my approval before ",
    "ask me before ",
    "ask for my approval before ",
    "obtain my approval before ",
    "hold every ",
    "attends ma validation avant ",
    "wait for my approval before ",
    "chiedimi prima di ",
    "chiedi la mia approvazione prima di ",
    "pregúntame antes de ",
    "preguntame antes de ",
    "pide mi aprobación antes de ",
    "pide mi aprobacion antes de ",
];
pub(super) const FORBIDDEN_MARKERS: &[&str] = &[
    "il est aussi absolument interdit de ",
    "il est aussi absolument interdit d'",
    "il est absolument interdit de ",
    "il est absolument interdit d'",
    "il est aussi interdit de ",
    "il est aussi interdit d'",
    "il est interdit de ",
    "il est interdit d'",
    "it is absolutely forbidden to ",
    "it is also absolutely forbidden to ",
    "it is forbidden to ",
    "never ",
    "do not ",
    "don't ",
    "nothing should be ",
    "ne jamais ",
    "è vietato ",
    "e vietato ",
    "è assolutamente vietato ",
    "está prohibido ",
    "esta prohibido ",
    "está absolutamente prohibido ",
    "nunca ",
];
pub(super) const STOP_MARKERS: &[&str] = &[
    "arrête-toi après",
    "aucune autre action n'est demandée",
    "no other step",
    "nothing else",
    "no further action",
];

/// Connectors that open a new clause whatever follows (a sequencing word must never
/// swallow an unknown verb as the previous object).
pub(super) const STRONG_CONNECTORS: &[&str] = &[
    ", puis ",
    " puis ",
    ", then ",
    " then ",
    ", mais ",
    " mais ",
    ", but ",
    " but ",
    ", poi ",
    " poi ",
    ", quindi ",
    " quindi ",
    ", luego ",
    " luego ",
    ", después ",
    " después ",
    ", despues ",
    " despues ",
];

/// Connectors that open a new clause only before a known head.
pub(super) const WEAK_CONNECTORS: &[&str] = &[
    ", et ", " et ", ", and ", " and ", ", e ", " e ", ", ed ", " ed ", ", y ", " y ", ", ",
];

/// One filler word after the first word of a clause (`passe ensuite la commande`).
pub(super) const SECOND_WORD_FILLERS: &[&str] = &[
    "ensuite",
    "alors",
    "then",
    "also",
    "aussi",
    "puis",
    "immédiatement",
    "immediately",
    "poi",
    "quindi",
    "anche",
    "luego",
    "después",
    "despues",
    "también",
    "tambien",
];

/// Coordinating connectors inside an object: a coordinated object is never explicit.
pub(super) const OBJECT_CONNECTORS: &[&str] = &[
    ", ",
    " and ",
    " et ",
    " or ",
    " ou ",
    " puis ",
    " then ",
    ";",
    " sans ",
    " without ",
    " mais ",
    " but ",
    " e ",
    " ed ",
    " y ",
    " o ",
    " poi ",
    " quindi ",
    " luego ",
    " pero ",
    " però ",
];

/// Category markers of a classify object (`classe en A, B ou C`, `classifica in A o B`).
pub(super) const CATEGORY_MARKERS: &[&str] =
    &[" en ", " into ", " as ", " in ", " come ", " como "];

/// Clause openers that state a negation (a prohibition or a restriction), per language.
pub(super) const NEGATION_OPENERS: &[&str] = &[
    "ne ", "n'", "do not ", "don't ", "never ", "no ", "aucun", "non ", "nunca ", "jamás ",
    "jamas ",
];

/// Clause openers that state a condition or a preservation, kept as a constraint.
pub(super) const CONSTRAINT_OPENERS: &[&str] = &[
    "si ",
    "if ",
    "lorsque ",
    "unless ",
    "laisse ",
    "laissez ",
    "leave ",
    "keep ",
    "conserve ",
    "garde ",
    "ignore ",
    "se ",
    "lascia ",
    "mantieni ",
    "conserva ",
    "ignora ",
    "deja ",
    "mantén ",
    "manten ",
];
