// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! The Spanish head table. Imperatives in the `tú` and `usted` forms and the
//! infinitive, plus the clitic forms a request writes (`guárdalo`, `léelo`), each
//! with and without its accent: a clitic is one more word of the closed table.
//! `resume` is deliberately absent: it is also the English verb that continues a
//! stopped job, and the reader never reads one word as two verbs.

use super::super::plan::{EffectVerb, Op};
use super::Head;

pub(super) const HEADS: &[(&str, Head)] = &[
    ("consultar", Head::Op(Op::Lookup)),
    ("recupere", Head::Op(Op::Lookup)),
    ("recuperar", Head::Op(Op::Lookup)),
    ("busca", Head::Choice(&[Op::Search, Op::Lookup])),
    ("busque", Head::Choice(&[Op::Search, Op::Lookup])),
    ("buscar", Head::Choice(&[Op::Search, Op::Lookup])),
    ("encuentra", Head::Choice(&[Op::Search, Op::Lookup])),
    ("encuentre", Head::Choice(&[Op::Search, Op::Lookup])),
    ("encontrar", Head::Choice(&[Op::Search, Op::Lookup])),
    ("lee", Head::Choice(&[Op::Read, Op::Lookup])),
    ("lea", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leer", Head::Choice(&[Op::Read, Op::Lookup])),
    ("léelo", Head::Choice(&[Op::Read, Op::Lookup])),
    ("léela", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leelo", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leela", Head::Choice(&[Op::Read, Op::Lookup])),
    ("descarga", Head::Op(Op::Fetch)),
    ("descargue", Head::Op(Op::Fetch)),
    ("descargar", Head::Op(Op::Fetch)),
    ("extrae", Head::Op(Op::Extract)),
    ("extraiga", Head::Op(Op::Extract)),
    ("extraer", Head::Op(Op::Extract)),
    ("clasifica", Head::Op(Op::Classify)),
    ("clasifique", Head::Op(Op::Classify)),
    ("clasificar", Head::Op(Op::Classify)),
    ("escribe", Head::Op(Op::Draft)),
    ("escriba", Head::Op(Op::Draft)),
    ("escriban", Head::Op(Op::Draft)),
    ("escribir", Head::Op(Op::Draft)),
    ("escríbelo", Head::Op(Op::Draft)),
    ("escríbela", Head::Op(Op::Draft)),
    ("escribelo", Head::Op(Op::Draft)),
    ("escribela", Head::Op(Op::Draft)),
    ("redacta", Head::Op(Op::Draft)),
    ("redacte", Head::Op(Op::Draft)),
    ("redacten", Head::Op(Op::Draft)),
    ("redactar", Head::Op(Op::Draft)),
    ("resuma", Head::Op(Op::Draft)),
    ("resuman", Head::Op(Op::Draft)),
    ("resumir", Head::Op(Op::Draft)),
    ("resúmelo", Head::Op(Op::Draft)),
    ("resúmela", Head::Op(Op::Draft)),
    ("resumelo", Head::Op(Op::Draft)),
    ("resumela", Head::Op(Op::Draft)),
    ("traduce", Head::Op(Op::Draft)),
    ("traduzca", Head::Op(Op::Draft)),
    ("traducir", Head::Op(Op::Draft)),
    ("tradúcelo", Head::Op(Op::Draft)),
    ("tradúcela", Head::Op(Op::Draft)),
    ("traducelo", Head::Op(Op::Draft)),
    ("traducela", Head::Op(Op::Draft)),
    ("preparar", Head::Op(Op::Draft)),
    ("corrija", Head::Op(Op::Draft)),
    ("corregir", Head::Op(Op::Draft)),
    ("calcula", Head::Op(Op::Compute)),
    ("calcule", Head::Op(Op::Compute)),
    ("calcular", Head::Op(Op::Compute)),
    ("compara", Head::Choice(&[Op::Compute, Op::Draft])),
    ("comparar", Head::Choice(&[Op::Compute, Op::Draft])),
    ("verifique", Head::Op(Op::Validate)),
    ("verificar", Head::Op(Op::Validate)),
    ("valida", Head::Op(Op::Validate)),
    ("validar", Head::Op(Op::Validate)),
    ("revisa", Head::Op(Op::Validate)),
    ("revisar", Head::Op(Op::Validate)),
    ("comprueba", Head::Op(Op::Validate)),
    ("comprobar", Head::Op(Op::Validate)),
    ("elimina los duplicados", Head::Dedup),
    ("quita los duplicados", Head::Dedup),
    ("evita los duplicados", Head::Dedup),
    ("guarda", Head::Effect(EffectVerb::Create)),
    ("guarde", Head::Effect(EffectVerb::Create)),
    ("guardar", Head::Effect(EffectVerb::Create)),
    ("guárdalo", Head::Effect(EffectVerb::Create)),
    ("guárdala", Head::Effect(EffectVerb::Create)),
    ("guárdalos", Head::Effect(EffectVerb::Create)),
    ("guárdalas", Head::Effect(EffectVerb::Create)),
    ("guardalo", Head::Effect(EffectVerb::Create)),
    ("guardala", Head::Effect(EffectVerb::Create)),
    ("guardalos", Head::Effect(EffectVerb::Create)),
    ("guardalas", Head::Effect(EffectVerb::Create)),
    ("cree", Head::Effect(EffectVerb::Create)),
    ("crear", Head::Effect(EffectVerb::Create)),
    ("abre", Head::Effect(EffectVerb::Create)),
    ("abra", Head::Effect(EffectVerb::Create)),
    ("abrir", Head::Effect(EffectVerb::Create)),
    ("envía", Head::Effect(EffectVerb::Send)),
    ("envíe", Head::Effect(EffectVerb::Send)),
    ("enviar", Head::Effect(EffectVerb::Send)),
    ("envíalo", Head::Effect(EffectVerb::Send)),
    ("envíala", Head::Effect(EffectVerb::Send)),
    ("envia", Head::Effect(EffectVerb::Send)),
    ("envie", Head::Effect(EffectVerb::Send)),
    ("envíes", Head::Effect(EffectVerb::Send)),
    ("envies", Head::Effect(EffectVerb::Send)),
    ("envialo", Head::Effect(EffectVerb::Send)),
    ("enviala", Head::Effect(EffectVerb::Send)),
    ("contacta", Head::Effect(EffectVerb::Send)),
    ("contactar", Head::Effect(EffectVerb::Send)),
    ("publica", Head::Effect(EffectVerb::Publish)),
    ("publique", Head::Effect(EffectVerb::Publish)),
    ("publicar", Head::Effect(EffectVerb::Publish)),
    ("publícalo", Head::Effect(EffectVerb::Publish)),
    ("publícala", Head::Effect(EffectVerb::Publish)),
    ("publicalo", Head::Effect(EffectVerb::Publish)),
    ("publicala", Head::Effect(EffectVerb::Publish)),
    ("publiques", Head::Effect(EffectVerb::Publish)),
    ("actualiza", Head::Effect(EffectVerb::Update)),
    ("actualice", Head::Effect(EffectVerb::Update)),
    ("actualizar", Head::Effect(EffectVerb::Update)),
    ("marca", Head::Effect(EffectVerb::Update)),
    ("marcar", Head::Effect(EffectVerb::Update)),
    ("reembolsa", Head::Effect(EffectVerb::Refund)),
    ("reembolse", Head::Effect(EffectVerb::Refund)),
    ("reembolsar", Head::Effect(EffectVerb::Refund)),
    ("pagar", Head::Effect(EffectVerb::Pay)),
    ("pague", Head::Effect(EffectVerb::Pay)),
    ("acredita", Head::Effect(EffectVerb::Pay)),
    ("acreditar", Head::Effect(EffectVerb::Pay)),
    ("fusiona", Head::Effect(EffectVerb::Merge)),
    ("fusionar", Head::Effect(EffectVerb::Merge)),
    ("eliminar", Head::Effect(EffectVerb::Delete)),
    ("borra", Head::Effect(EffectVerb::Delete)),
    ("borre", Head::Effect(EffectVerb::Delete)),
    ("borrar", Head::Effect(EffectVerb::Delete)),
    ("notifique", Head::Effect(EffectVerb::Notify)),
    ("notificar", Head::Effect(EffectVerb::Notify)),
    ("avisa", Head::Effect(EffectVerb::Notify)),
    ("avisar", Head::Effect(EffectVerb::Notify)),
    ("ejecuta", Head::Effect(EffectVerb::Other)),
    ("ejecutar", Head::Effect(EffectVerb::Other)),
    ("activa", Head::Effect(EffectVerb::Other)),
    ("activar", Head::Effect(EffectVerb::Other)),
];

/// Heads that write named content to a path once a destination follows.
pub(super) const WRITE_HEADS: &[&str] = &[
    "escribe",
    "escriba",
    "escriban",
    "escribir",
    "escríbelo",
    "escríbela",
    "escribelo",
    "escribela",
    "guarda",
    "guarde",
    "guardar",
    "guárdalo",
    "guárdala",
    "guárdalos",
    "guárdalas",
    "guardalo",
    "guardala",
    "guardalos",
    "guardalas",
];
