// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! The head-verb tables of the deterministic reader: what a clause may open with.
//!
//! Every table is closed. A head names one operation, a small finite choice of
//! operations, an effect verb or the deduplication obligation; the reader never
//! guesses a head it does not list. English and French share one table; Italian
//! and Spanish live in their own files. The longest matching phrase wins, and a
//! match must end at a word boundary (`look up` before `look`, never `lookups`).

use super::super::plan::{EffectVerb, Op};

pub(crate) enum Head {
    Op(Op),
    Choice(&'static [Op]),
    Effect(EffectVerb),
    Dedup,
}

/// Every head table, in lookup order (the longest phrase wins across all of them).
pub(super) const TABLES: &[&[(&str, Head)]] = &[EN_FR, super::it::HEADS, super::es::HEADS];

/// Heads that write named content to a path (`écris … dans ./x.md`, `salvalo in
/// ./x.md`): with a path and a destination connector, the clause is a write effect.
pub(super) fn writes_to_path(phrase: &str) -> bool {
    WRITE_HEADS.contains(&phrase)
        || super::it::WRITE_HEADS.contains(&phrase)
        || super::es::WRITE_HEADS.contains(&phrase)
}

const WRITE_HEADS: &[&str] = &[
    "write",
    "écris",
    "écrivez",
    "écrire",
    "enregistre",
    "enregistrez",
    "enregistrer",
    "record",
];

/// Longest phrase first. Lowercase, apostrophes normalized to `'`.
pub(super) const EN_FR: &[(&str, Head)] = &[
    ("va chercher", Head::Op(Op::Lookup)),
    ("allez chercher", Head::Op(Op::Lookup)),
    ("look up", Head::Op(Op::Lookup)),
    ("looks up", Head::Op(Op::Lookup)),
    ("lookup", Head::Op(Op::Lookup)),
    ("pull up", Head::Op(Op::Lookup)),
    ("consulte", Head::Op(Op::Lookup)),
    ("consultez", Head::Op(Op::Lookup)),
    ("consulter", Head::Op(Op::Lookup)),
    ("interroge", Head::Op(Op::Lookup)),
    ("interrogez", Head::Op(Op::Lookup)),
    ("interroger", Head::Op(Op::Lookup)),
    ("récupère", Head::Op(Op::Lookup)),
    ("récupérez", Head::Op(Op::Lookup)),
    ("récupérer", Head::Op(Op::Lookup)),
    ("retrieve", Head::Op(Op::Lookup)),
    ("retrieves", Head::Op(Op::Lookup)),
    ("query", Head::Op(Op::Lookup)),
    ("retrouve", Head::Choice(&[Op::Lookup, Op::Search])),
    ("retrouvez", Head::Choice(&[Op::Lookup, Op::Search])),
    ("retrouver", Head::Choice(&[Op::Lookup, Op::Search])),
    ("cherche", Head::Choice(&[Op::Search, Op::Lookup])),
    ("cherchez", Head::Choice(&[Op::Search, Op::Lookup])),
    ("chercher", Head::Choice(&[Op::Search, Op::Lookup])),
    ("recherche", Head::Choice(&[Op::Search, Op::Lookup])),
    ("recherchez", Head::Choice(&[Op::Search, Op::Lookup])),
    ("rechercher", Head::Choice(&[Op::Search, Op::Lookup])),
    ("search", Head::Choice(&[Op::Search, Op::Lookup])),
    ("find", Head::Choice(&[Op::Search, Op::Lookup])),
    ("lis", Head::Choice(&[Op::Read, Op::Lookup])),
    ("lisez", Head::Choice(&[Op::Read, Op::Lookup])),
    ("lire", Head::Choice(&[Op::Read, Op::Lookup])),
    ("read", Head::Choice(&[Op::Read, Op::Lookup])),
    ("fetch", Head::Op(Op::Fetch)),
    ("download", Head::Op(Op::Fetch)),
    ("télécharge", Head::Op(Op::Fetch)),
    ("téléchargez", Head::Op(Op::Fetch)),
    ("télécharger", Head::Op(Op::Fetch)),
    ("extrais", Head::Op(Op::Extract)),
    ("extrayez", Head::Op(Op::Extract)),
    ("extraire", Head::Op(Op::Extract)),
    ("extract", Head::Op(Op::Extract)),
    ("extracts", Head::Op(Op::Extract)),
    ("determine its department", Head::Op(Op::Classify)),
    ("determine the department", Head::Op(Op::Classify)),
    ("classe", Head::Op(Op::Classify)),
    ("classez", Head::Op(Op::Classify)),
    ("classer", Head::Op(Op::Classify)),
    ("classifie", Head::Op(Op::Classify)),
    ("classifiez", Head::Op(Op::Classify)),
    ("classifier", Head::Op(Op::Classify)),
    ("trie", Head::Op(Op::Classify)),
    ("triez", Head::Op(Op::Classify)),
    ("trier", Head::Op(Op::Classify)),
    ("route", Head::Op(Op::Classify)),
    ("routez", Head::Op(Op::Classify)),
    ("router", Head::Op(Op::Classify)),
    ("classify", Head::Op(Op::Classify)),
    ("categorize", Head::Op(Op::Classify)),
    ("categorise", Head::Op(Op::Classify)),
    ("triage", Head::Op(Op::Classify)),
    ("propose par écrit", Head::Op(Op::Draft)),
    ("propose in writing", Head::Op(Op::Draft)),
    ("prépare", Head::Op(Op::Draft)),
    ("préparez", Head::Op(Op::Draft)),
    ("préparer", Head::Op(Op::Draft)),
    ("rédige", Head::Op(Op::Draft)),
    ("rédigez", Head::Op(Op::Draft)),
    ("rédiger", Head::Op(Op::Draft)),
    ("résume", Head::Op(Op::Draft)),
    ("résumez", Head::Op(Op::Draft)),
    ("résumer", Head::Op(Op::Draft)),
    ("traduis", Head::Op(Op::Draft)),
    ("traduisez", Head::Op(Op::Draft)),
    ("traduire", Head::Op(Op::Draft)),
    ("écris", Head::Op(Op::Draft)),
    ("écrivez", Head::Op(Op::Draft)),
    ("écrire", Head::Op(Op::Draft)),
    ("draft", Head::Op(Op::Draft)),
    ("drafts", Head::Op(Op::Draft)),
    ("write", Head::Op(Op::Draft)),
    ("prepare", Head::Op(Op::Draft)),
    ("summarize", Head::Op(Op::Draft)),
    ("summarise", Head::Op(Op::Draft)),
    ("translate", Head::Op(Op::Draft)),
    ("compose", Head::Op(Op::Draft)),
    ("calcule", Head::Op(Op::Compute)),
    ("calculez", Head::Op(Op::Compute)),
    ("calculer", Head::Op(Op::Compute)),
    ("compute", Head::Op(Op::Compute)),
    ("calculate", Head::Op(Op::Compute)),
    ("repère", Head::Op(Op::Compute)),
    ("repérez", Head::Op(Op::Compute)),
    ("repérer", Head::Op(Op::Compute)),
    ("compare", Head::Choice(&[Op::Compute, Op::Draft])),
    ("comparez", Head::Choice(&[Op::Compute, Op::Draft])),
    ("comparer", Head::Choice(&[Op::Compute, Op::Draft])),
    (
        "répartis leur révision entre plusieurs agents",
        Head::Op(Op::Explore),
    ),
    ("répartis", Head::Op(Op::Explore)),
    ("répartissez", Head::Op(Op::Explore)),
    ("répartir", Head::Op(Op::Explore)),
    ("distribute", Head::Op(Op::Explore)),
    ("delegate", Head::Op(Op::Explore)),
    ("délègue", Head::Op(Op::Explore)),
    ("explore", Head::Op(Op::Explore)),
    ("investigate", Head::Op(Op::Explore)),
    ("corrige", Head::Op(Op::Draft)),
    ("corrigez", Head::Op(Op::Draft)),
    ("corriger", Head::Op(Op::Draft)),
    ("correct", Head::Op(Op::Draft)),
    ("revise", Head::Op(Op::Draft)),
    ("fais relire", Head::Op(Op::Validate)),
    ("faites relire", Head::Op(Op::Validate)),
    ("relis", Head::Op(Op::Validate)),
    ("relire", Head::Op(Op::Validate)),
    ("review", Head::Op(Op::Validate)),
    ("proofread", Head::Op(Op::Validate)),
    ("valide", Head::Op(Op::Validate)),
    ("validez", Head::Op(Op::Validate)),
    ("valider", Head::Op(Op::Validate)),
    ("validate", Head::Op(Op::Validate)),
    ("verify", Head::Op(Op::Validate)),
    ("dédoublonne", Head::Dedup),
    ("dédoublonnez", Head::Dedup),
    ("dédoublonner", Head::Dedup),
    ("déduplique", Head::Dedup),
    ("dédupliquez", Head::Dedup),
    ("dédupliquer", Head::Dedup),
    ("évite les doublons", Head::Dedup),
    ("dedupe", Head::Dedup),
    ("deduplicate", Head::Dedup),
    ("remove duplicates", Head::Dedup),
    ("prevent duplicates", Head::Dedup),
    ("passe la commande", Head::Effect(EffectVerb::Order)),
    ("passez la commande", Head::Effect(EffectVerb::Order)),
    ("place the order", Head::Effect(EffectVerb::Order)),
    ("issue store credits", Head::Effect(EffectVerb::Pay)),
    ("issue a refund", Head::Effect(EffectVerb::Refund)),
    ("issue refunds", Head::Effect(EffectVerb::Refund)),
    ("issue any refund", Head::Effect(EffectVerb::Refund)),
    ("mets à jour", Head::Effect(EffectVerb::Update)),
    ("met à jour", Head::Effect(EffectVerb::Update)),
    ("mettre à jour", Head::Effect(EffectVerb::Update)),
    ("crée", Head::Effect(EffectVerb::Create)),
    ("créez", Head::Effect(EffectVerb::Create)),
    ("créer", Head::Effect(EffectVerb::Create)),
    ("create", Head::Effect(EffectVerb::Create)),
    ("ouvre", Head::Effect(EffectVerb::Create)),
    ("ouvrez", Head::Effect(EffectVerb::Create)),
    ("ouvrir", Head::Effect(EffectVerb::Create)),
    ("open", Head::Effect(EffectVerb::Create)),
    ("enregistre", Head::Effect(EffectVerb::Create)),
    ("enregistrez", Head::Effect(EffectVerb::Create)),
    ("enregistrer", Head::Effect(EffectVerb::Create)),
    ("record", Head::Effect(EffectVerb::Create)),
    ("envoie", Head::Effect(EffectVerb::Send)),
    ("envoyez", Head::Effect(EffectVerb::Send)),
    ("envoyer", Head::Effect(EffectVerb::Send)),
    ("send", Head::Effect(EffectVerb::Send)),
    ("email", Head::Effect(EffectVerb::Send)),
    ("contacte", Head::Effect(EffectVerb::Send)),
    ("contactez", Head::Effect(EffectVerb::Send)),
    ("contacter", Head::Effect(EffectVerb::Send)),
    ("contact", Head::Effect(EffectVerb::Send)),
    ("publie", Head::Effect(EffectVerb::Publish)),
    ("publiez", Head::Effect(EffectVerb::Publish)),
    ("publier", Head::Effect(EffectVerb::Publish)),
    ("publish", Head::Effect(EffectVerb::Publish)),
    ("poste", Head::Effect(EffectVerb::Publish)),
    ("postez", Head::Effect(EffectVerb::Publish)),
    ("poster", Head::Effect(EffectVerb::Publish)),
    ("post", Head::Effect(EffectVerb::Publish)),
    ("marque", Head::Effect(EffectVerb::Update)),
    ("marquez", Head::Effect(EffectVerb::Update)),
    ("marquer", Head::Effect(EffectVerb::Update)),
    ("mark", Head::Effect(EffectVerb::Update)),
    ("update", Head::Effect(EffectVerb::Update)),
    ("rembourse", Head::Effect(EffectVerb::Refund)),
    ("remboursez", Head::Effect(EffectVerb::Refund)),
    ("rembourser", Head::Effect(EffectVerb::Refund)),
    ("refund", Head::Effect(EffectVerb::Refund)),
    ("refunds", Head::Effect(EffectVerb::Refund)),
    ("reimburse", Head::Effect(EffectVerb::Refund)),
    ("crédite", Head::Effect(EffectVerb::Pay)),
    ("créditez", Head::Effect(EffectVerb::Pay)),
    ("credit", Head::Effect(EffectVerb::Pay)),
    ("paie", Head::Effect(EffectVerb::Pay)),
    ("payez", Head::Effect(EffectVerb::Pay)),
    ("payer", Head::Effect(EffectVerb::Pay)),
    ("pay", Head::Effect(EffectVerb::Pay)),
    ("fusionne", Head::Effect(EffectVerb::Merge)),
    ("fusionnez", Head::Effect(EffectVerb::Merge)),
    ("fusionner", Head::Effect(EffectVerb::Merge)),
    ("merge", Head::Effect(EffectVerb::Merge)),
    ("supprime", Head::Effect(EffectVerb::Delete)),
    ("supprimez", Head::Effect(EffectVerb::Delete)),
    ("supprimer", Head::Effect(EffectVerb::Delete)),
    ("delete", Head::Effect(EffectVerb::Delete)),
    ("notifie", Head::Effect(EffectVerb::Notify)),
    ("notifiez", Head::Effect(EffectVerb::Notify)),
    ("notifier", Head::Effect(EffectVerb::Notify)),
    ("notify", Head::Effect(EffectVerb::Notify)),
    ("alert", Head::Effect(EffectVerb::Notify)),
    ("déclenche", Head::Effect(EffectVerb::Other)),
    ("déclenchez", Head::Effect(EffectVerb::Other)),
    ("déclencher", Head::Effect(EffectVerb::Other)),
    ("trigger", Head::Effect(EffectVerb::Other)),
    ("execute", Head::Effect(EffectVerb::Other)),
    ("exécute", Head::Effect(EffectVerb::Other)),
];
