// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! `#[derive(EventTaskId)]` — auto-generates `task_id()` method for event enums.
//!
//! Variant annotations:
//! - `#[has_task_id]` — extracts `task_id: Arc<str>` field
//! - `#[has_task_id(field = "parent_task_id")]` — custom field name
//! - `#[has_task_id(optional)]` — handles `Option<Arc<str>>`
//! - No attribute → returns `None`

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, Meta};

pub fn derive(input: &DeriveInput) -> TokenStream {
    let name = &input.ident;

    let data = match &input.data {
        Data::Enum(data) => data,
        Data::Struct(_) | Data::Union(_) => {
            return syn::Error::new_spanned(input, "EventTaskId can only be derived for enums")
                .to_compile_error();
        }
    };

    let mut arms = Vec::new();

    for variant in &data.variants {
        let variant_ident = &variant.ident;

        // Find #[has_task_id] or #[has_task_id(...)] attribute
        let attr = variant
            .attrs
            .iter()
            .find(|a| a.path().is_ident("has_task_id"));

        let Some(attr) = attr else {
            // No #[has_task_id] → return None
            let pattern = match &variant.fields {
                Fields::Named(_) => quote! { Self::#variant_ident { .. } },
                Fields::Unnamed(_) => quote! { Self::#variant_ident(..) },
                Fields::Unit => quote! { Self::#variant_ident },
            };
            arms.push(quote! { #pattern => None, });
            continue;
        };

        // Parse attribute arguments
        let (field_name, is_optional) = match &attr.meta {
            // #[has_task_id] — bare path, default field name "task_id"
            Meta::Path(_) => ("task_id".to_string(), false),
            // #[has_task_id(...)] — parse arguments
            Meta::List(list) => match parse_has_task_id_args(list) {
                Ok(result) => result,
                Err(err) => return err,
            },
            Meta::NameValue(_) => {
                return syn::Error::new_spanned(
                    attr,
                    "expected #[has_task_id], #[has_task_id(field = \"name\")], or #[has_task_id(optional)]",
                )
                .to_compile_error();
            }
        };

        let field_ident = format_ident!("{}", field_name);

        if is_optional {
            // Option<Arc<str>> → task_id.as_ref().map(|s| s.as_ref())
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => #field_ident.as_ref().map(|s| s.as_ref()),
            });
        } else {
            // Arc<str> → Some(task_id)
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => Some(#field_ident),
            });
        }
    }

    quote! {
        impl #name {
            /// Extract task_id if event is task-related.
            ///
            /// Auto-generated by `#[derive(EventTaskId)]`.
            pub fn task_id(&self) -> Option<&str> {
                match self {
                    #(#arms)*
                }
            }
        }
    }
}

/// Parse arguments inside `#[has_task_id(...)]`.
///
/// Returns `(field_name, is_optional)`.
fn parse_has_task_id_args(
    list: &syn::MetaList,
) -> Result<(String, bool), TokenStream> {
    let tokens_str = list.tokens.to_string();
    let trimmed = tokens_str.trim();

    // #[has_task_id(optional)]
    if trimmed == "optional" {
        return Ok(("task_id".to_string(), true));
    }

    // #[has_task_id(field = "parent_task_id")]
    if let Some(rest) = trimmed.strip_prefix("field") {
        let rest = rest.trim();
        if let Some(rest) = rest.strip_prefix('=') {
            let rest = rest.trim();
            // Remove quotes
            if let Some(name) = rest.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
                return Ok((name.to_string(), false));
            }
        }
    }

    // #[has_task_id(field = "name", optional)]
    // For simplicity, check if "optional" is present
    let is_optional = trimmed.contains("optional");
    if let Some(rest) = trimmed.strip_prefix("field") {
        let rest = rest.trim().strip_prefix('=').map(str::trim).unwrap_or("");
        // Find the quoted string
        if let Some(start) = rest.find('"') {
            if let Some(end) = rest[start + 1..].find('"') {
                let name = &rest[start + 1..start + 1 + end];
                return Ok((name.to_string(), is_optional));
            }
        }
    }

    Err(syn::Error::new_spanned(
        list,
        "expected #[has_task_id], #[has_task_id(optional)], or #[has_task_id(field = \"name\")]",
    )
    .to_compile_error())
}
