// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! `#[derive(EventTaskId)]` — auto-generates `task_id()` method for event enums.
//!
//! Variant annotations:
//! - `#[has_task_id]` — extracts `task_id: Arc<str>` field (named variants only)
//! - `#[has_task_id(field = "parent_task_id")]` — custom field name
//! - `#[has_task_id(optional)]` — handles `Option<Arc<str>>`
//! - No attribute → returns `None`

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, Meta};

pub fn derive(input: &DeriveInput) -> TokenStream {
    let name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let data = match &input.data {
        Data::Enum(data) => data,
        Data::Struct(_) | Data::Union(_) => {
            return syn::Error::new_spanned(input, "EventTaskId can only be derived for enums")
                .to_compile_error();
        }
    };

    let mut arms = Vec::new();

    for variant in &data.variants {
        let variant_ident = &variant.ident;

        // Find #[has_task_id] or #[has_task_id(...)] attribute
        let attr = variant
            .attrs
            .iter()
            .find(|a| a.path().is_ident("has_task_id"));

        let Some(attr) = attr else {
            // No #[has_task_id] → return None
            let pattern = match &variant.fields {
                Fields::Named(_) => quote! { Self::#variant_ident { .. } },
                Fields::Unnamed(_) => quote! { Self::#variant_ident(..) },
                Fields::Unit => quote! { Self::#variant_ident },
            };
            arms.push(quote! { #pattern => None, });
            continue;
        };

        // Guard: #[has_task_id] requires named fields (struct-like variant)
        if !matches!(&variant.fields, Fields::Named(_)) {
            return syn::Error::new_spanned(
                variant_ident,
                "#[has_task_id] requires a named-field variant (struct-like)",
            )
            .to_compile_error();
        }

        // Parse attribute arguments
        let (field_name, is_optional) = match &attr.meta {
            // #[has_task_id] — bare path, default field name "task_id"
            Meta::Path(_) => ("task_id".to_string(), false),
            // #[has_task_id(...)] — parse arguments
            Meta::List(list) => match parse_has_task_id_args(list) {
                Ok(result) => result,
                Err(err) => return err,
            },
            Meta::NameValue(_) => {
                return syn::Error::new_spanned(
                    attr,
                    "expected #[has_task_id], #[has_task_id(field = \"name\")], or #[has_task_id(optional)]",
                )
                .to_compile_error();
            }
        };

        // Validate that the field actually exists in the variant
        let fields = match &variant.fields {
            Fields::Named(f) => f,
            Fields::Unnamed(_) | Fields::Unit => unreachable!("guarded above"),
        };
        let field_exists = fields
            .named
            .iter()
            .any(|f| f.ident.as_ref().is_some_and(|i| *i == field_name));
        if !field_exists {
            return syn::Error::new_spanned(
                variant_ident,
                format!(
                    "variant `{}` has #[has_task_id] but no field named `{}`",
                    variant_ident, field_name
                ),
            )
            .to_compile_error();
        }

        let field_ident = format_ident!("{}", field_name);

        if is_optional {
            // Option<Arc<str>> → task_id.as_ref().map(|s| s.as_ref())
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => #field_ident.as_ref().map(|s| s.as_ref()),
            });
        } else {
            // Arc<str> → Some(task_id)
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => Some(#field_ident),
            });
        }
    }

    quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            /// Extract task_id if event is task-related.
            ///
            /// Auto-generated by `#[derive(EventTaskId)]`.
            pub fn task_id(&self) -> Option<&str> {
                match self {
                    #(#arms)*
                }
            }
        }
    }
}

/// Parse arguments inside `#[has_task_id(...)]` using proper syn parsing.
///
/// Supported forms:
/// - `#[has_task_id(optional)]` → `("task_id", true)`
/// - `#[has_task_id(field = "name")]` → `("name", false)`
///
/// Returns `(field_name, is_optional)`.
fn parse_has_task_id_args(
    list: &syn::MetaList,
) -> Result<(String, bool), TokenStream> {
    // Try parsing as a single identifier first: #[has_task_id(optional)]
    if let Ok(ident) = syn::parse2::<syn::Ident>(list.tokens.clone()) {
        if ident == "optional" {
            return Ok(("task_id".to_string(), true));
        }
        return Err(syn::Error::new_spanned(
            &ident,
            format!("unknown argument `{ident}`, expected `optional` or `field = \"name\"`"),
        )
        .to_compile_error());
    }

    // Parse as punctuated MetaNameValue: #[has_task_id(field = "name")]
    let pairs: syn::punctuated::Punctuated<syn::Meta, syn::Token![,]> =
        match syn::parse::Parser::parse2(
            syn::punctuated::Punctuated::parse_terminated,
            list.tokens.clone(),
        ) {
            Ok(p) => p,
            Err(e) => return Err(e.to_compile_error()),
        };

    let mut field_name = None;
    let mut is_optional = false;

    for meta in &pairs {
        match meta {
            // `optional` (bare identifier)
            syn::Meta::Path(path) if path.is_ident("optional") => {
                is_optional = true;
            }
            // `field = "name"`
            syn::Meta::NameValue(nv) if nv.path.is_ident("field") => {
                #[allow(clippy::wildcard_enum_match_arm)]
                match &nv.value {
                    syn::Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Str(s),
                        ..
                    }) => {
                        field_name = Some(s.value());
                    }
                    _ => {
                        return Err(syn::Error::new_spanned(
                            &nv.value,
                            "expected string literal for field name",
                        )
                        .to_compile_error());
                    }
                }
            }
            syn::Meta::Path(p) => {
                return Err(syn::Error::new_spanned(
                    p,
                    "expected `optional` or `field = \"name\"`",
                )
                .to_compile_error());
            }
            syn::Meta::List(l) => {
                return Err(syn::Error::new_spanned(
                    l,
                    "expected `optional` or `field = \"name\"`",
                )
                .to_compile_error());
            }
            syn::Meta::NameValue(nv) => {
                return Err(syn::Error::new_spanned(
                    &nv.path,
                    "expected `optional` or `field = \"name\"`",
                )
                .to_compile_error());
            }
        }
    }

    Ok((
        field_name.unwrap_or_else(|| "task_id".to_string()),
        is_optional,
    ))
}
