// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! `#[derive(EventTaskId)]` — auto-generates `task_id()` method for event enums.
//!
//! Variant annotations:
//! - `#[has_task_id]` — extracts `task_id: Arc<str>` field (named variants only)
//! - `#[has_task_id(field = "parent_task_id")]` — custom field name
//! - `#[has_task_id(optional)]` — handles `Option<Arc<str>>`
//! - No attribute → returns `None`

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, Meta};

pub fn derive(input: &DeriveInput) -> TokenStream {
    let name = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let data = match &input.data {
        Data::Enum(data) => data,
        Data::Struct(_) | Data::Union(_) => {
            return syn::Error::new_spanned(input, "EventTaskId can only be derived for enums")
                .to_compile_error();
        }
    };

    let mut arms = Vec::new();

    for variant in &data.variants {
        let variant_ident = &variant.ident;

        // Find #[has_task_id] or #[has_task_id(...)] attribute
        let attr = variant
            .attrs
            .iter()
            .find(|a| a.path().is_ident("has_task_id"));

        let Some(attr) = attr else {
            // No #[has_task_id] → return None
            let pattern = match &variant.fields {
                Fields::Named(_) => quote! { Self::#variant_ident { .. } },
                Fields::Unnamed(_) => quote! { Self::#variant_ident(..) },
                Fields::Unit => quote! { Self::#variant_ident },
            };
            arms.push(quote! { #pattern => None, });
            continue;
        };

        // Guard: #[has_task_id] requires named fields (struct-like variant)
        if !matches!(&variant.fields, Fields::Named(_)) {
            return syn::Error::new_spanned(
                variant_ident,
                "#[has_task_id] requires a named-field variant (struct-like)",
            )
            .to_compile_error();
        }

        // Parse attribute arguments
        let (field_name, is_optional) = match &attr.meta {
            // #[has_task_id] — bare path, default field name "task_id"
            Meta::Path(_) => ("task_id".to_string(), false),
            // #[has_task_id(...)] — parse arguments
            Meta::List(list) => match parse_has_task_id_args(list) {
                Ok(result) => result,
                Err(err) => return err,
            },
            Meta::NameValue(_) => {
                return syn::Error::new_spanned(
                    attr,
                    "expected #[has_task_id], #[has_task_id(field = \"name\")], or #[has_task_id(optional)]",
                )
                .to_compile_error();
            }
        };

        let field_ident = format_ident!("{}", field_name);

        if is_optional {
            // Option<Arc<str>> → task_id.as_ref().map(|s| s.as_ref())
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => #field_ident.as_ref().map(|s| s.as_ref()),
            });
        } else {
            // Arc<str> → Some(task_id)
            arms.push(quote! {
                Self::#variant_ident { #field_ident, .. } => Some(#field_ident),
            });
        }
    }

    quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            /// Extract task_id if event is task-related.
            ///
            /// Auto-generated by `#[derive(EventTaskId)]`.
            pub fn task_id(&self) -> Option<&str> {
                match self {
                    #(#arms)*
                }
            }
        }
    }
}

/// Parse arguments inside `#[has_task_id(...)]`.
///
/// Supported forms:
/// - `#[has_task_id(optional)]` → `("task_id", true)`
/// - `#[has_task_id(field = "name")]` → `("name", false)`
///
/// Returns `(field_name, is_optional)`.
fn parse_has_task_id_args(
    list: &syn::MetaList,
) -> Result<(String, bool), TokenStream> {
    let tokens_str = list.tokens.to_string();
    let trimmed = tokens_str.trim();

    // #[has_task_id(optional)]
    if trimmed == "optional" {
        return Ok(("task_id".to_string(), true));
    }

    // #[has_task_id(field = "name")]
    if let Some(rest) = trimmed.strip_prefix("field") {
        let rest = rest.trim();
        if let Some(rest) = rest.strip_prefix('=') {
            let rest = rest.trim();
            // Find the quoted field name — handle both `"name"` and `"name" , optional`
            if let Some(after_quote) = rest.strip_prefix('"') {
                if let Some(end_idx) = after_quote.find('"') {
                    let field_name = &after_quote[..end_idx];
                    // Check if there's a trailing ", optional" after the closing quote
                    let remainder = after_quote[end_idx + 1..].trim();
                    let is_optional = remainder.strip_prefix(',')
                        .map(str::trim)
                        .is_some_and(|r| r == "optional");
                    return Ok((field_name.to_string(), is_optional));
                }
            }
        }
    }

    Err(syn::Error::new_spanned(
        list,
        "expected #[has_task_id(optional)] or #[has_task_id(field = \"name\")]",
    )
    .to_compile_error())
}
