// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! `#[derive(NikaErrorCode)]` — auto-generates `code()` method from `#[nika_code]` attributes.
//!
//! Each variant must have exactly one of:
//! - `#[nika_code("NIKA-XXX")]` — returns the literal string
//! - `#[nika_code(delegate)]` — calls `.code()` on the inner value (tuple variants only)

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, Lit, Meta, MetaList};

pub fn derive(input: &DeriveInput) -> TokenStream {
    let name = &input.ident;

    let data = match &input.data {
        Data::Enum(data) => data,
        Data::Struct(_) | Data::Union(_) => {
            return syn::Error::new_spanned(input, "NikaErrorCode can only be derived for enums")
                .to_compile_error();
        }
    };

    let mut arms = Vec::new();

    for variant in &data.variants {
        let variant_ident = &variant.ident;

        // Find #[nika_code(...)] attribute
        let nika_code_attr = variant.attrs.iter().find(|attr| attr.path().is_ident("nika_code"));

        let attr = match nika_code_attr {
            Some(a) => a,
            None => {
                return syn::Error::new_spanned(
                    variant_ident,
                    format!(
                        "variant `{}` is missing #[nika_code(\"...\")]  or #[nika_code(delegate)]",
                        variant_ident
                    ),
                )
                .to_compile_error();
            }
        };

        // Parse the attribute content
        let meta = match &attr.meta {
            Meta::List(list) => list,
            Meta::Path(_) | Meta::NameValue(_) => {
                return syn::Error::new_spanned(
                    attr,
                    "expected #[nika_code(\"NIKA-XXX\")] or #[nika_code(delegate)]",
                )
                .to_compile_error();
            }
        };

        // Check if it's delegate or a string literal
        let tokens_str = meta.tokens.to_string();

        if tokens_str.trim() == "delegate" {
            // Delegation pattern: call .code() on the inner value
            match &variant.fields {
                Fields::Unnamed(fields) if fields.unnamed.len() == 1 => {
                    arms.push(quote! {
                        Self::#variant_ident(inner) => inner.code(),
                    });
                }
                Fields::Named(_) | Fields::Unnamed(_) | Fields::Unit => {
                    return syn::Error::new_spanned(
                        variant_ident,
                        "#[nika_code(delegate)] requires a single-field tuple variant",
                    )
                    .to_compile_error();
                }
            }
        } else {
            // Parse as string literal
            let code_str = match parse_string_from_meta_list(meta) {
                Ok(s) => s,
                Err(e) => return e.to_compile_error(),
            };

            // Generate the match arm based on variant shape
            let pattern = match &variant.fields {
                Fields::Named(_) => quote! { Self::#variant_ident { .. } },
                Fields::Unnamed(_) => quote! { Self::#variant_ident(..) },
                Fields::Unit => quote! { Self::#variant_ident },
            };

            arms.push(quote! {
                #pattern => #code_str,
            });
        }
    }

    quote! {
        impl #name {
            /// Get the error code (e.g., "NIKA-001").
            ///
            /// Auto-generated by `#[derive(NikaErrorCode)]`.
            pub fn code(&self) -> &'static str {
                match self {
                    #(#arms)*
                }
            }
        }
    }
}

/// Parse a string literal from a `MetaList` like `nika_code("NIKA-001")`.
fn parse_string_from_meta_list(list: &MetaList) -> Result<String, syn::Error> {
    let lit: Lit = syn::parse2(list.tokens.clone()).map_err(|_| {
        syn::Error::new_spanned(
            list,
            "expected a string literal: #[nika_code(\"NIKA-XXX\")]",
        )
    })?;

    // syn::Lit is #[non_exhaustive] — wildcard required for forward compat
    #[allow(clippy::wildcard_enum_match_arm)]
    match lit {
        Lit::Str(s) => Ok(s.value()),
        _ => Err(syn::Error::new_spanned(
            &lit,
            "expected a string literal: #[nika_code(\"NIKA-XXX\")]",
        )),
    }
}
