# Per-repo estate rules. The tool is shared and lives in nika-estate;
# these declarations are ours. FILES carries the per-file exceptions,
# PATTERNS the ordered globs that cover everything else.
#
# ROOT, SELF, RULES and CLASSES are injected by the tool into this
# module namespace before it executes. They are therefore undefined as
# far as a linter reading this file alone can tell, hence the noqa: a
# placeholder assignment would satisfy the linter and then OVERWRITE the
# injected value, which is worse than the warning.

# Per-repo estate rules. The tool is shared and lives in nika-estate;
# these declarations are ours. FILES are the per-file exceptions,
# PATTERNS the ordered globs that cover the rest (first match wins).

FILES = [
    {
        "path": SELF,  # noqa: F821
        "class": "pinned-copy",
        "evidence": "the shared estate tool, mirrored byte-for-byte from supernovae-st/nika-estate · editing it here is a lost gesture: change it upstream, bump ESTATE_PIN, re-mirror",
        "derivation": {
            "tool": "curl the tool from nika-estate at the rev named in ESTATE_PIN",
            "gate": "the `mirror` job byte-compares scripts/estate.py against nika-estate@ESTATE_PIN and fails the run on any difference",
            "inputs": ["ESTATE_PIN", "supernovae-st/nika-estate@<ESTATE_PIN>:scripts/estate.py"],
        },
    },
    {
        "path": "ESTATE_PIN",
        "class": "authored-pin",
        "evidence": "its own header: 'Bump deliberately: edit this' \u00b7 the rev the shared estate tool is mirrored from, and the INPUT the mirror gate compares against",
    },
    {
        "path": "SPEC_PIN",
        "class": "authored-pin",
        "evidence": "its own header: 'Advanced by .github/workflows/spec-pin-heal.yml (PR-only · the Diamond CI tests leg judges at the new pin). Consumed by diamond-ci.yml. Never HEAD.'",
    },
    {
        "path": "Cargo.lock",
        "class": "generated",
        "evidence": "cargo's resolver writes it; no human edits a lockfile",
        "derivation": {
            "tool": "cargo (dependency resolution against Cargo.toml + crates/*/Cargo.toml)",
            "gate": "--locked builds across the CI rails (diamond-ci.yml · release.yml) — a stale lock fails resolution",
            "inputs": ["Cargo.toml", "crates/*/Cargo.toml"],
        },
    },
    {
        "path": "fuzz/Cargo.lock",
        "class": "generated",
        "evidence": "cargo's resolver writes it for the fuzz workspace; no human edits a lockfile",
        "derivation": {
            "tool": "cargo (dependency resolution against fuzz/Cargo.toml)",
            "gate": "fuzz-nightly.yml builds the fuzz workspace",
            "inputs": ["fuzz/Cargo.toml"],
        },
    },
    {
        "path": "CHANGELOG.md",
        "class": "generated",
        "evidence": "changelog-cliff.yml commits 'docs(changelog): append <tag> — auto-generated' on tag push (git-cliff), branch chore/changelog-<tag>, PR body 'Review, edit if needed, merge'",
        "derivation": {
            "tool": "git-cliff (cliff.toml) via .github/workflows/changelog-cliff.yml on tag push",
            "gate": "idempotence guard in the workflow (existing '## [<ver>]' section skips) + human review at the PR",
            "inputs": ["git tag + commit history", "cliff.toml"],
        },
        "note": "generated with a human gate — the maintainer may amend the section at PR review",
    },
    {
        "path": "docs/adr/index.toml",
        "class": "generated",
        "evidence": "in-file marker: 'ADR Index -- auto-generated by scripts/adr/generate-index.sh · Do not edit manually'",
        "derivation": {
            "tool": "scripts/adr/generate-index.sh",
            "gate": "scripts/hygiene/check-adr-index-parity.sh",
            "inputs": ["docs/adr/adr-*.md YAML frontmatter"],
        },
    },
    {
        "path": "crates/nika-catalog/data/model-pricing.toml",
        "class": "generated",
        "evidence": "in-file marker '── GENERATED · do not hand-edit' + [meta] source=https://models.dev/api.json · as_of · source_sha256_16 — a vendored snapshot, refreshed at maintenance time, never a runtime fetch",
        "derivation": {
            "tool": "bash scripts/refresh-pricing.sh (emission laws matched to src/data/models.rs lookup semantics)",
            # MEASURED 2026-08-12: catalog-verify.yml imports all_embeddings
            # and all_mcp_servers ONLY (crates/nika-catalog-verify/src/main.rs:36)
            # and never reads a pricing rule. The old string here named it as
            # this snapshot's gate, which made every reader believe the price
            # was watched. A claimed-but-unfired gate is worse than no gate.
            "gate": "NONE. catalog-verify.yml probes embeddings + mcp servers only (all_embeddings, all_mcp_servers) and never a pricing rule, so this snapshot is UNWATCHED. Two guards EXIST and neither runs: drift-watch.nika.yaml hashes upstream against [meta].sha256 (no cron calls it) and pricing-differential.py cross-checks models.dev against LiteLLM (its workflow has no schedule).",
            "inputs": ["https://models.dev/api.json (MIT · sst/models.dev)"],
        },
    },
    {
        "path": ".claude/CLAUDE.md",
        "class": "authored",
        "evidence": "hand-written harness entry for the Diamond rebuild (rules prose · gate map)",
        "note": "carries the '<!-- AUTO-GENERATED by scripts/refresh-status.sh — do not edit by hand -->' status block (vector 23 parity-enforced) — a tool-maintained block inside an authored file",
    },
    {
        "path": "ROADMAP.md",
        "class": "authored",
        "evidence": "hand-written roadmap prose (real-semver ladder · layer plan)",
        "note": "ROADMAP.md:98 carries the same refresh-status.sh AUTO-GENERATED status block — a tool-maintained block inside an authored file",
    },
    {
        "path": "media/README.md",
        "class": "authored",
        "evidence": "the authored rules for the media lanes ('No fake commands · No fake output · budgets · Never edit exports by hand')",
    },
]

# ── patterns: ordered glob rows — FIRST-MATCH-WINS ──────────────────────────

PATTERNS = [
    {
        "glob": "crates/nika-pack/pack/**",
        "class": "pinned-copy",
        "evidence": "crates/nika-pack/src/lib.rs:16 'The snapshot under pack/ is vendored by scripts/sync-pack.sh' — a byte-copy of the spec surface, never edited here",
        "derivation": {
            "tool": "bash scripts/sync-pack.sh <nika-spec checkout at SPEC_PIN> — spec-pin-heal.yml advances the pin and pack together, and Diamond CI refuses any pack differing from spec@SPEC_PIN",
            "gate": "cargo test -p nika-pack → tests/pack_integrity.rs re-hashes every workflow (sha256_16 over lean text) against pack/examples/manifest.yaml",
            "inputs": ["supernovae-st/nika-spec@SPEC_PIN: VERSION · QUICKSTART.md · canon.yaml · conformance/coverage-matrix.tsv · design/{tokens,motion}.yaml · spec/ · schemas/ · examples/ · templates/ · stdlib/*.md"],
        },
        "note": "pack/examples/manifest.yaml is itself GENERATED upstream (spec scripts/showcase-projector.py) — vendored here as part of the copy",
    },
    {
        "glob": "crates/nika-runtime/fixtures/adversarial/**",
        "class": "testimonial",
        "evidence": "attack.nika.yaml + expected.json pairs consumed by crates/nika-runtime/src/adversarial/tests.rs — the injection red-team battery owned by the runtime",
    },
    {
        "glob": "fuzz/corpus/**",
        "class": "testimonial",
        "evidence": "fuzz-nightly.yml:12-13 'Corpus is committed under fuzz/corpus/ (seeded from nika-spec examples + conformance fixtures) · new corpus discovered by CI is NOT pushed back'",
    },
    {
        "glob": "scripts/test/battery/**",
        "class": "testimonial",
        "evidence": "manifest.tsv + s*.nika.yaml scenarios consumed by scripts/test/structured-live-battery.sh (Rail C · the LIVE provider rail)",
    },
    {
        "glob": "crates/*/public-api.txt",
        "class": "generated",
        "evidence": ".github/workflows/public-api.yml 'diff each covered lib crate' byte-compares each snapshot against cargo public-api output; macOS renders differently, so snapshots regenerate FROM THE UBUNTU ARTIFACT (workflow comment)",
        "derivation": {
            "tool": "cargo public-api -p <crate> --omit auto-trait-impls > crates/<crate>/public-api.txt (DEFAULT features · the CI job shape — all-features drags platform deps into the render · cargo-public-api 0.51.0 pinned · the public-api-actual CI artifact stays the judge)",
            "gate": ".github/workflows/public-api.yml (drift → RED) + semver-checks.yml (breaking-vs-additive) + scripts/ci/public-api-coverage-baseline.txt (the monotonic floor)",
            "inputs": ["crates/<crate>/src/**", "crates/<crate>/Cargo.toml", "cargo-public-api 0.51.0"],
        },
    },
    {
        "glob": "crates/**/src/**",
        "class": "authored",
        "evidence": "the code — SPDX AGPL-3.0-or-later headers · 12-gate admission (ADR-003) · zero-unwrap discipline; spot-checked file heads carry no generation marker (grep hits for 'generated' are prose mentions, not markers)",
    },
    {
        "glob": "crates/**/tests/**",
        "class": "authored",
        "evidence": "crate-owned tests + fixtures under tests/ — written with the crate per gate discipline, no generation markers",
    },
    {
        "glob": "crates/**",
        "class": "authored",
        "evidence": "the remaining crate surface — Cargo.toml manifests · build.rs · benches · READMEs · hand-curated data catalogs (llm-providers · mcp-servers · embeddings · model-capabilities, probed daily by catalog-verify.yml); the pricing snapshot is excepted in files:",
        "note": "scripts/sync-pack.sh is the ONE vendoring lane; the divergent crate-local duplicate was retired",
    },
    {
        "glob": "fuzz/**",
        "class": "authored",
        "evidence": "4 hand-written fuzz targets + the fuzz workspace config (fuzz/Cargo.toml · .gitignore); corpus excepted above, lockfile in files:",
    },
    {
        "glob": "docs/adr/**",
        "class": "authored",
        "evidence": "per-decision records authored at decision time (scripts/adr/new.sh scaffolds · adr-seal-check hook seals); index.toml excepted in files:",
    },
    {
        "glob": "docs/testimonials/**",
        "class": "testimonial",
        "evidence": "privacy-sanitized machine receipts captured from complete verification runs; their validator binds the tested commit, pre-run census, invocation, input blobs, accounting, and artifact hashes",
    },
    {
        "glob": "docs/**",
        "class": "authored",
        "evidence": "crate-specs · architecture prose · perf notes — no generation markers at file heads",
    },
    {
        "glob": "scripts/**",
        "class": "authored",
        "evidence": "hand-written gates · hooks · hygiene vectors · media lanes; the ratchet baselines (scripts/ci/*-baseline.txt · scripts/hygiene/baselines/) are hand-kept monotonic floors ('Never remove a line by hand')",
    },
    {
        "glob": ".github/workflows/**",
        "class": "authored",
        "evidence": "hand-written CI rails, comments narrate design decisions; the heal lanes here rewrite OTHER files (spec-pin-heal.yml → SPEC_PIN + pack · changelog-cliff.yml → CHANGELOG.md), nothing rewrites the workflows themselves",
    },
    {
        "glob": ".github/**",
        "class": "authored",
        "evidence": "issue/PR templates · CODEOWNERS · dependabot config — hand-written review policy",
    },
    {
        "glob": ".agents/**",
        "class": "authored",
        "evidence": "the engine-owned portable release kit; wave-sweep advances its manifests with the engine and nika-plugins mirrors these bytes only from immutable engine release tags via resync-mirror.py",
        "note": "direction is engine tag → nika-plugins mirror; clients-resync owns only clients.registry.yaml and must never overwrite this tree from a moving downstream main branch",
    },
    {
        "glob": ".claude/**",
        "class": "authored",
        "evidence": "harness rules · skills · commands for the Diamond rebuild — hand-written; .claude/CLAUDE.md excepted in files: (carries the refresh-status.sh auto-block)",
    },
    {
        "glob": ".claude-plugin/**",
        "class": "authored",
        "evidence": "the Claude plugin marketplace manifest — hand-written",
    },
    {
        "glob": ".cargo/**",
        "class": "authored",
        "evidence": "cargo config · audit.toml · mutants.toml — hand-kept workspace policy",
    },
    {
        "glob": "media/**",
        "class": "generated",
        "evidence": "media/README.md: 'Never edit exports by hand. Edit the motion scene or fixture, then re-render' — gifs/posters/videos/social render from scripts/media/motion/ scenes + tapes; raw/ transcripts are captured from the real binary",
        "derivation": {
            "tool": "scripts/media/render-motion.mjs + render-tape.sh + capture-transcripts.sh (scenes: scripts/media/motion/ · fixtures: scripts/media/fixtures/ · tapes: scripts/media/tapes/)",
            "gate": "scripts/media/validate-media.sh (every shown workflow passes nika check · budgets enforced)",
            "inputs": ["scripts/media/motion/**", "scripts/media/fixtures/**", "scripts/media/tapes/**", "the real nika binary (captured transcripts)"],
        },
        "note": "media/README.md excepted in files: (the authored rules for these lanes)",
    },
    {
        "glob": "examples/**",
        "class": "authored",
        "evidence": "examples/README.md — a pointer README (the runnable examples live in the vendored pack + the spec repo)",
    },
    {
        "glob": "changelog.d/**",
        "class": "authored",
        "evidence": "changelog.d/README.md — one hand-written bullet per change, authored by whoever makes the change; scripts/release/changelog-assemble.sh only CONSUMES them (--fold splices and deletes) and never writes one",
        "note": "the README is permanent by design: a rule matching nothing is a coverage hole, and every fragment is deleted at fold time",
    },
    {
        "glob": "*",
        "class": "authored",
        "evidence": "root prose + config surface (README · DIAMOND · LICENSE · llms.txt · Cargo.toml · deny/clippy/cliff/typos toml · lefthook.yml · flake.nix · Dockerfile) — no generation markers at file heads; CHANGELOG.md · Cargo.lock · SPEC_PIN · ROADMAP.md excepted in files:",
    },
    {
        "glob": "**",
        "class": "authored",
        "evidence": "no evidence gathered — honesty over completeness (the catchall; anything landing here is reported under unverified:)",
        "note": "unverified-default",
    },
]
