// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
//! The trigger reader's vocabulary: the words that state a cadence (a day, a week, a month, an
//! hour, a minute, in six languages), the time introducers, the named times, the webhook
//! words, the sequencing and event heads, the completion, time and arrival words. Knowledge
//! only: the folds that read a trigger phrase live in nika-compile's `trigger.rs`. Moved here
//! from nika-compile at the 15k prod-LOC wall (2026-09-23), unchanged.

/// Words that state a daily cadence (EN · FR · IT · ES · DE · PT, folded).
pub const DAILY: &[&str] = &[
    "morning",
    "mornings",
    "evening",
    "evenings",
    "night",
    "nights",
    "noon",
    "midday",
    "midnight",
    "day",
    "days",
    "daily",
    "matin",
    "matins",
    "soir",
    "soirs",
    "jour",
    "jours",
    "quotidien",
    "quotidienne",
    "quotidiennement",
    "midi",
    "minuit",
    "mattina",
    "sera",
    "giorno",
    "giorni",
    "quotidiano",
    "manana",
    "mananas",
    "tarde",
    "noche",
    "dia",
    "dias",
    "diario",
    "diaria",
    "diariamente",
    "morgen",
    "abend",
    "tag",
    "taglich",
    "manha",
    "manhas",
    "noite",
    "noites",
];

/// Words that state a weekday cadence: every working day.
pub const WEEKDAYS: &[&str] = &[
    "weekday",
    "weekdays",
    "workday",
    "workdays",
    "ouvre",
    "ouvres",
    "ouvrable",
    "ouvrables",
    "lavorativo",
    "lavorativi",
    "laborable",
    "laborables",
    "werktag",
    "werktags",
];

/// Words that state a weekly cadence: a week or a named day of the week.
pub const WEEKLY: &[&str] = &[
    "week",
    "weeks",
    "weekly",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "semaine",
    "semaines",
    "hebdomadaire",
    "hebdo",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
    "dimanche",
    "lundis",
    "mardis",
    "mercredis",
    "jeudis",
    "vendredis",
    "samedis",
    "dimanches",
    "settimana",
    "settimanale",
    "lunedi",
    "martedi",
    "mercoledi",
    "giovedi",
    "venerdi",
    "sabato",
    "domenica",
    "semana",
    "semanal",
    "lunes",
    "martes",
    "miercoles",
    "jueves",
    "viernes",
    "sabado",
    "domingo",
    "segunda",
    "segunda-feira",
    "terca",
    "terca-feira",
    "quarta",
    "quarta-feira",
    "quinta",
    "quinta-feira",
    "sexta",
    "sexta-feira",
    "woche",
    "wochentlich",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "sonntag",
];

pub const MONTHLY: &[&str] = &[
    "month",
    "months",
    "monthly",
    "mois",
    "mensuel",
    "mensuelle",
    "mese",
    "mesi",
    "mensile",
    "mes",
    "meses",
    "mensual",
    "monat",
    "monate",
    "monatlich",
];

pub const HOURLY: &[&str] = &[
    "hour",
    "hours",
    "hourly",
    "heure",
    "heures",
    "horaire",
    "ora",
    "ore",
    "hora",
    "horas",
    "stunde",
    "stunden",
    "stundlich",
];

pub const MINUTELY: &[&str] = &["minute", "minutes", "minuto", "minuti", "minutos"];

/// Words that introduce a time of day ("at 9", "à 9h", "alle 7", "a las 8", "um 9 uhr",
/// "às 7h" — the Portuguese « às » folds to « as »).
pub const AT: &[&str] = &["at", "a", "as", "alle", "um", "vers", "around", "towards"];

/// Determiners that may sit between the introducer and the number ("a las 8").
pub const BETWEEN: &[&str] = &["las", "les", "le", "la", "the", "l"];

/// Units that follow a time number and belong to it, never to a cadence.
pub const TIME_UNITS: &[&str] = &[
    "h", "hours", "hour", "heures", "heure", "uhr", "horas", "ore",
];

/// Words that name a time of day outright.
pub const NAMED_TIMES: &[(&str, &str)] = &[
    ("noon", "12:00"),
    ("midday", "12:00"),
    ("midi", "12:00"),
    ("mezzogiorno", "12:00"),
    ("mediodia", "12:00"),
    ("mittag", "12:00"),
    ("midnight", "00:00"),
    ("minuit", "00:00"),
    ("mezzanotte", "00:00"),
    ("medianoche", "00:00"),
    ("mitternacht", "00:00"),
];

/// Words that name an inbound HTTP call.
pub const WEBHOOK: &[&str] = &["webhook", "webhooks", "hook", "hooks"];

/// Heads that order the program's own work (EN · FR · ES · IT · DE · PT, folded).
pub const SEQUENCE_HEADS: &[&str] = &[
    "once ",
    "after ",
    "then ",
    "apres ",
    "puis ",
    "ensuite ",
    "une fois ",
    "despues ",
    "luego ",
    "una vez ",
    "dopo ",
    "poi ",
    "nach ",
    "danach ",
    "sobald alle ",
    "depois ",
];

/// Heads that open an outside event (folded).
pub const EVENT_HEADS: &[&str] = &[
    "when ",
    "whenever ",
    "each time ",
    "every time ",
    "quand ",
    "lorsque ",
    "des que ",
    "des qu'",
    "chaque fois ",
    "a chaque fois ",
    "cuando ",
    "cada vez ",
    "quando ",
    "ogni volta ",
    "wenn ",
    "sobald ",
    "jedes mal ",
    "sempre que ",
    "toda vez ",
];

/// Words that say the program's own work is finished: a `when` over them is a sequence.
pub const COMPLETION_WORDS: &[&str] = &[
    "done",
    "finished",
    "complete",
    "completed",
    "termine",
    "terminee",
    "fini",
    "finie",
    "acheve",
    "terminado",
    "terminada",
    "finalizado",
    "completato",
    "completata",
    "finito",
    "fertig",
    "abgeschlossen",
    "concluido",
    "pronto",
];

/// Words that name a moment or a period of the calendar (folded): a quantifier over them
/// is a cadence, not a distribution over items.
pub const TIME_WORDS: &[&str] = &[
    "morning",
    "mornings",
    "noon",
    "afternoon",
    "evening",
    "evenings",
    "night",
    "nights",
    "midnight",
    "day",
    "days",
    "daily",
    "weekday",
    "weekdays",
    "week",
    "weeks",
    "weekly",
    "month",
    "months",
    "monthly",
    "quarter",
    "hour",
    "hours",
    "hourly",
    "minute",
    "minutes",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "matin",
    "matins",
    "midi",
    "soir",
    "soirs",
    "nuit",
    "jour",
    "jours",
    "quotidien",
    "semaine",
    "semaines",
    "hebdomadaire",
    "mois",
    "mensuel",
    "heure",
    "heures",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
    "dimanche",
    "lundis",
    "mardis",
    "mercredis",
    "jeudis",
    "vendredis",
    "samedis",
    "dimanches",
    "manana",
    "mananas",
    "tarde",
    "noche",
    "dia",
    "dias",
    "diario",
    "semana",
    "semanas",
    "semanal",
    "mes",
    "meses",
    "mensual",
    "hora",
    "horas",
    "lunes",
    "martes",
    "miercoles",
    "jueves",
    "viernes",
    "sabado",
    "domingo",
    "mattina",
    "mattino",
    "sera",
    "notte",
    "giorno",
    "giorni",
    "giornaliero",
    "settimana",
    "settimane",
    "settimanale",
    "mese",
    "mesi",
    "mensile",
    "ora",
    "ore",
    "lunedi",
    "martedi",
    "mercoledi",
    "giovedi",
    "venerdi",
    "sabato",
    "domenica",
    "morgen",
    "morgens",
    "mittag",
    "abend",
    "abends",
    "nacht",
    "tag",
    "tage",
    "taglich",
    "woche",
    "wochen",
    "wochentlich",
    "monat",
    "monate",
    "monatlich",
    "stunde",
    "stunden",
    "stundlich",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "sonntag",
    "manha",
    "manhas",
    "noite",
    "noites",
    "diariamente",
];

/// Words that mark an item as arriving with the invocation (an event stream, not a set that
/// exists somewhere): « each incoming brief », « chaque nouveau ticket », « cada correo
/// recibido », « ogni nuova richiesta », « jede eingehende Mail », « cada novo pedido ».
pub const ARRIVAL_WORDS: &[&str] = &[
    "incoming",
    "new",
    "arriving",
    "received",
    "submitted",
    "entrant",
    "entrante",
    "entrants",
    "entrantes",
    "nouveau",
    "nouvel",
    "nouvelle",
    "nouveaux",
    "nouvelles",
    "recu",
    "recue",
    "recus",
    "recues",
    "qui arrive",
    "nuevo",
    "nueva",
    "nuevos",
    "nuevas",
    "recibido",
    "recibida",
    "recibidos",
    "recibidas",
    "nuovo",
    "nuova",
    "nuovi",
    "nuove",
    "in arrivo",
    "ricevuto",
    "ricevuta",
    "ricevuti",
    "ricevute",
    "neu",
    "neue",
    "neuen",
    "neues",
    "neuer",
    "eingehend",
    "eingehende",
    "eingehenden",
    "eingegangen",
    "eingegangene",
    "novo",
    "nova",
    "novos",
    "novas",
    "recebido",
    "recebida",
    "recebidos",
    "recebidas",
    "a chegar",
];

/// Phrases that ask for the work again and again without saying when (FR · EN, folded, whole
/// words): « régulièrement », « de temps en temps », « regularly », « from time to time ». The
/// cadence is the human's to state, never the compiler's to guess. The adjectives (« un
/// rapport régulier », « a regular report ») and the frequency words (« souvent », « often »)
/// are left out: they also name a kind of thing (« une expression régulière », « regular
/// customers ») or a proportion, not a repetition of the run.
pub const RECURRENT: &[&str] = &[
    "regulierement",
    "periodiquement",
    "de temps en temps",
    "de temps a autre",
    "a intervalles reguliers",
    "a intervalle regulier",
    "de facon reguliere",
    "de maniere reguliere",
    "sur une base reguliere",
    "regularly",
    "periodically",
    "from time to time",
    "every so often",
    "at regular intervals",
    "on a regular basis",
];

/// The whole answers that say each run starts by hand, never on a cadence (FR · EN, folded).
pub const MANUAL: &[&str] = &[
    "manual",
    "manually",
    "by hand",
    "on demand",
    "manuel",
    "manuelle",
    "manuellement",
    "a la main",
    "a la demande",
    "sur demande",
];
