// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>
//! The cadence words the reader reads itself: the words that state a cadence (a day, a week,
//! a month, an hour, a minute, in six languages) and the recurrences stated without their
//! cadence. Knowledge only: the folds that read a trigger phrase live in `nika-compile-trigger`,
//! with the words only they read (the time introducers, the named times, the webhook, sequence,
//! event, completion, time and arrival words, the manual answers · ADR-142). Moved here from
//! nika-compile at the 15k prod-LOC wall (2026-09-23), unchanged.

/// Words that state a daily cadence (EN · FR · IT · ES · DE · PT, folded).
pub const DAILY: &[&str] = &[
    "morning",
    "mornings",
    "evening",
    "evenings",
    "night",
    "nights",
    "noon",
    "midday",
    "midnight",
    "day",
    "days",
    "daily",
    "matin",
    "matins",
    "soir",
    "soirs",
    "jour",
    "jours",
    "quotidien",
    "quotidienne",
    "quotidiennement",
    "midi",
    "minuit",
    "mattina",
    "sera",
    "giorno",
    "giorni",
    "quotidiano",
    "manana",
    "mananas",
    "tarde",
    "noche",
    "dia",
    "dias",
    "diario",
    "diaria",
    "diariamente",
    "morgen",
    "abend",
    "tag",
    "taglich",
    "manha",
    "manhas",
    "noite",
    "noites",
];

/// Words that state a weekday cadence: every working day.
pub const WEEKDAYS: &[&str] = &[
    "weekday",
    "weekdays",
    "workday",
    "workdays",
    "ouvre",
    "ouvres",
    "ouvrable",
    "ouvrables",
    "lavorativo",
    "lavorativi",
    "laborable",
    "laborables",
    "werktag",
    "werktags",
];

/// Words that state a weekly cadence: a week or a named day of the week.
pub const WEEKLY: &[&str] = &[
    "week",
    "weeks",
    "weekly",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "semaine",
    "semaines",
    "hebdomadaire",
    "hebdo",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
    "dimanche",
    "lundis",
    "mardis",
    "mercredis",
    "jeudis",
    "vendredis",
    "samedis",
    "dimanches",
    "settimana",
    "settimanale",
    "lunedi",
    "martedi",
    "mercoledi",
    "giovedi",
    "venerdi",
    "sabato",
    "domenica",
    "semana",
    "semanal",
    "lunes",
    "martes",
    "miercoles",
    "jueves",
    "viernes",
    "sabado",
    "domingo",
    "segunda",
    "segunda-feira",
    "terca",
    "terca-feira",
    "quarta",
    "quarta-feira",
    "quinta",
    "quinta-feira",
    "sexta",
    "sexta-feira",
    "woche",
    "wochentlich",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "sonntag",
];

pub const MONTHLY: &[&str] = &[
    "month",
    "months",
    "monthly",
    "mois",
    "mensuel",
    "mensuelle",
    "mese",
    "mesi",
    "mensile",
    "mes",
    "meses",
    "mensual",
    "monat",
    "monate",
    "monatlich",
];

pub const HOURLY: &[&str] = &[
    "hour",
    "hours",
    "hourly",
    "heure",
    "heures",
    "horaire",
    "ora",
    "ore",
    "hora",
    "horas",
    "stunde",
    "stunden",
    "stundlich",
];

pub const MINUTELY: &[&str] = &["minute", "minutes", "minuto", "minuti", "minutos"];

/// Phrases that ask for the work again and again without saying when (FR · EN, folded, whole
/// words): « régulièrement », « de temps en temps », « regularly », « from time to time ». The
/// cadence is the human's to state, never the compiler's to guess. The adjectives (« un
/// rapport régulier », « a regular report ») and the frequency words (« souvent », « often »)
/// are left out: they also name a kind of thing (« une expression régulière », « regular
/// customers ») or a proportion, not a repetition of the run.
pub const RECURRENT: &[&str] = &[
    "regulierement",
    "periodiquement",
    "de temps en temps",
    "de temps a autre",
    "a intervalles reguliers",
    "a intervalle regulier",
    "de facon reguliere",
    "de maniere reguliere",
    "sur une base reguliere",
    "regularly",
    "periodically",
    "from time to time",
    "every so often",
    "at regular intervals",
    "on a regular basis",
];
