// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 SuperNovae Studio <contact@supernovae.studio>

//! The Italian head table. Imperatives in the second person singular and plural and
//! the infinitive, plus the clitic forms a request writes (`salvalo`, `leggila`):
//! a clitic is one more word of the closed table, never a suffix the reader strips.

use super::super::plan::{EffectVerb, Op};
use super::Head;

pub(super) const HEADS: &[(&str, Head)] = &[
    ("consulta", Head::Op(Op::Lookup)),
    ("consultate", Head::Op(Op::Lookup)),
    ("consultare", Head::Op(Op::Lookup)),
    ("recupera", Head::Op(Op::Lookup)),
    ("recuperate", Head::Op(Op::Lookup)),
    ("recuperare", Head::Op(Op::Lookup)),
    ("interroga", Head::Op(Op::Lookup)),
    ("interrogare", Head::Op(Op::Lookup)),
    ("cerca", Head::Choice(&[Op::Search, Op::Lookup])),
    ("cercate", Head::Choice(&[Op::Search, Op::Lookup])),
    ("cercare", Head::Choice(&[Op::Search, Op::Lookup])),
    ("trova", Head::Choice(&[Op::Search, Op::Lookup])),
    ("trovate", Head::Choice(&[Op::Search, Op::Lookup])),
    ("trovare", Head::Choice(&[Op::Search, Op::Lookup])),
    ("leggi", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leggete", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leggere", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leggilo", Head::Choice(&[Op::Read, Op::Lookup])),
    ("leggila", Head::Choice(&[Op::Read, Op::Lookup])),
    ("scarica", Head::Op(Op::Fetch)),
    ("scaricate", Head::Op(Op::Fetch)),
    ("scaricare", Head::Op(Op::Fetch)),
    ("estrai", Head::Op(Op::Extract)),
    ("estraete", Head::Op(Op::Extract)),
    ("estrarre", Head::Op(Op::Extract)),
    ("classifica", Head::Op(Op::Classify)),
    ("classificate", Head::Op(Op::Classify)),
    ("classificare", Head::Op(Op::Classify)),
    ("smista", Head::Op(Op::Classify)),
    ("smistate", Head::Op(Op::Classify)),
    ("smistare", Head::Op(Op::Classify)),
    ("scrivi", Head::Op(Op::Draft)),
    ("scrivete", Head::Op(Op::Draft)),
    ("scrivere", Head::Op(Op::Draft)),
    ("scrivilo", Head::Op(Op::Draft)),
    ("scrivila", Head::Op(Op::Draft)),
    ("riassumi", Head::Op(Op::Draft)),
    ("riassumete", Head::Op(Op::Draft)),
    ("riassumere", Head::Op(Op::Draft)),
    ("riassumilo", Head::Op(Op::Draft)),
    ("riassumila", Head::Op(Op::Draft)),
    ("redigi", Head::Op(Op::Draft)),
    ("redigete", Head::Op(Op::Draft)),
    ("redigere", Head::Op(Op::Draft)),
    ("traduci", Head::Op(Op::Draft)),
    ("traducete", Head::Op(Op::Draft)),
    ("tradurre", Head::Op(Op::Draft)),
    ("traducilo", Head::Op(Op::Draft)),
    ("traducila", Head::Op(Op::Draft)),
    ("prepara", Head::Op(Op::Draft)),
    ("preparate", Head::Op(Op::Draft)),
    ("preparare", Head::Op(Op::Draft)),
    ("componi", Head::Op(Op::Draft)),
    ("comporre", Head::Op(Op::Draft)),
    ("correggi", Head::Op(Op::Draft)),
    ("correggete", Head::Op(Op::Draft)),
    ("correggere", Head::Op(Op::Draft)),
    ("fammi", Head::Op(Op::Draft)),
    ("fatemi", Head::Op(Op::Draft)),
    ("facci", Head::Op(Op::Draft)),
    ("fai", Head::Op(Op::Draft)),
    ("fate", Head::Op(Op::Draft)),
    ("produci", Head::Op(Op::Draft)),
    ("producete", Head::Op(Op::Draft)),
    ("produrre", Head::Op(Op::Draft)),
    ("genera", Head::Op(Op::Draft)),
    ("generare", Head::Op(Op::Draft)),
    ("elabora", Head::Op(Op::Draft)),
    ("elaborare", Head::Op(Op::Draft)),
    ("calcola", Head::Op(Op::Compute)),
    ("calcolate", Head::Op(Op::Compute)),
    ("calcolare", Head::Op(Op::Compute)),
    ("confronta", Head::Choice(&[Op::Compute, Op::Draft])),
    ("confrontare", Head::Choice(&[Op::Compute, Op::Draft])),
    ("verifica", Head::Op(Op::Validate)),
    ("verificate", Head::Op(Op::Validate)),
    ("verificare", Head::Op(Op::Validate)),
    ("rileggi", Head::Op(Op::Validate)),
    ("rileggere", Head::Op(Op::Validate)),
    ("convalida", Head::Op(Op::Validate)),
    ("convalidare", Head::Op(Op::Validate)),
    ("deduplica", Head::Dedup),
    ("elimina i duplicati", Head::Dedup),
    ("rimuovi i duplicati", Head::Dedup),
    ("evita i duplicati", Head::Dedup),
    ("salva", Head::Effect(EffectVerb::Create)),
    ("salvate", Head::Effect(EffectVerb::Create)),
    ("salvare", Head::Effect(EffectVerb::Create)),
    ("salvalo", Head::Effect(EffectVerb::Create)),
    ("salvala", Head::Effect(EffectVerb::Create)),
    ("salvali", Head::Effect(EffectVerb::Create)),
    ("salvale", Head::Effect(EffectVerb::Create)),
    ("salvatelo", Head::Effect(EffectVerb::Create)),
    ("salvatela", Head::Effect(EffectVerb::Create)),
    ("crea", Head::Effect(EffectVerb::Create)),
    ("creare", Head::Effect(EffectVerb::Create)),
    ("apri", Head::Effect(EffectVerb::Create)),
    ("aprite", Head::Effect(EffectVerb::Create)),
    ("aprire", Head::Effect(EffectVerb::Create)),
    ("registra", Head::Effect(EffectVerb::Create)),
    ("registrare", Head::Effect(EffectVerb::Create)),
    ("invia", Head::Effect(EffectVerb::Send)),
    ("inviate", Head::Effect(EffectVerb::Send)),
    ("inviare", Head::Effect(EffectVerb::Send)),
    ("invialo", Head::Effect(EffectVerb::Send)),
    ("inviala", Head::Effect(EffectVerb::Send)),
    ("manda", Head::Effect(EffectVerb::Send)),
    ("mandare", Head::Effect(EffectVerb::Send)),
    ("contatta", Head::Effect(EffectVerb::Send)),
    ("contattare", Head::Effect(EffectVerb::Send)),
    ("pubblica", Head::Effect(EffectVerb::Publish)),
    ("pubblicate", Head::Effect(EffectVerb::Publish)),
    ("pubblicare", Head::Effect(EffectVerb::Publish)),
    ("pubblicalo", Head::Effect(EffectVerb::Publish)),
    ("pubblicala", Head::Effect(EffectVerb::Publish)),
    ("aggiorna", Head::Effect(EffectVerb::Update)),
    ("aggiornate", Head::Effect(EffectVerb::Update)),
    ("aggiornare", Head::Effect(EffectVerb::Update)),
    ("segna", Head::Effect(EffectVerb::Update)),
    ("segnare", Head::Effect(EffectVerb::Update)),
    ("rimborsa", Head::Effect(EffectVerb::Refund)),
    ("rimborsate", Head::Effect(EffectVerb::Refund)),
    ("rimborsare", Head::Effect(EffectVerb::Refund)),
    ("paga", Head::Effect(EffectVerb::Pay)),
    ("pagate", Head::Effect(EffectVerb::Pay)),
    ("pagare", Head::Effect(EffectVerb::Pay)),
    ("accredita", Head::Effect(EffectVerb::Pay)),
    ("accreditare", Head::Effect(EffectVerb::Pay)),
    ("unisci", Head::Effect(EffectVerb::Merge)),
    ("unire", Head::Effect(EffectVerb::Merge)),
    ("elimina", Head::Effect(EffectVerb::Delete)),
    ("eliminare", Head::Effect(EffectVerb::Delete)),
    ("cancella", Head::Effect(EffectVerb::Delete)),
    ("cancellare", Head::Effect(EffectVerb::Delete)),
    ("notifica", Head::Effect(EffectVerb::Notify)),
    ("notificate", Head::Effect(EffectVerb::Notify)),
    ("notificare", Head::Effect(EffectVerb::Notify)),
    ("avvisa", Head::Effect(EffectVerb::Notify)),
    ("avvisare", Head::Effect(EffectVerb::Notify)),
    ("esegui", Head::Effect(EffectVerb::Other)),
    ("eseguire", Head::Effect(EffectVerb::Other)),
    ("attiva", Head::Effect(EffectVerb::Other)),
    ("attivare", Head::Effect(EffectVerb::Other)),
];

/// Heads that write named content to a path once a destination follows.
pub(super) const WRITE_HEADS: &[&str] = &[
    "scrivi",
    "scrivete",
    "scrivere",
    "scrivilo",
    "scrivila",
    "salva",
    "salvate",
    "salvare",
    "salvalo",
    "salvala",
    "salvali",
    "salvale",
    "salvatelo",
    "salvatela",
    "registra",
    "registrare",
];

/// Heads that make something: a draft only of produced content.
pub(super) const MAKE_HEADS: &[&str] = &[
    "fammi",
    "fatemi",
    "facci",
    "fai",
    "fate",
    "produci",
    "producete",
    "produrre",
    "genera",
    "generare",
    "elabora",
    "elaborare",
];
